<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__phone-e08a4a3c-4d83-4f4c-aa78-28a39b_481823</name>
   <tag></tag>
   <elementGuidId>39d271ac-bff8-4378-bcd4-088ab12d6dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phone-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6ebf13f-5333-47e1-90ad-b8a619a4bd66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760</value>
      <webElementGuid>3e8c66a1-5bab-4f30-83d3-eb1d7d30700b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>48ba8ec2-ef6b-474d-b38a-6cc87034e1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-input</value>
      <webElementGuid>efad633e-da1e-47f9-aa4a-60972263c05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>a00af139-8401-4e94-871b-530179159137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>f016b2a3-932d-43d0-b671-3bddef703731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>+351 9</value>
      <webElementGuid>a1bfeb39-2e92-4c83-8d2c-568fed4487da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760&quot;)</value>
      <webElementGuid>1097ac28-f3ed-4f38-a022-4db30c8ad849</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']</value>
      <webElementGuid>b9c841d7-ca6a-4e53-b0c4-e81d9b61a705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hsForm_e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']/fieldset[3]/div/div/div/input</value>
      <webElementGuid>01c512da-1cc7-4cc3-ab0c-53f6b5808a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>dfcaa5db-b329-493f-b38f-816a1d2182a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'phone-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760' and @type = 'tel']</value>
      <webElementGuid>dd3ce2d5-d39c-432c-92a4-c6bc4368ad4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
