<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_RoleC-Level  VPHead  DirectorManager_c565cc</name>
   <tag></tag>
   <elementGuidId>22c29677-d137-4657-aa70-d6cf3a7ab93c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#what_is_your_role_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='what_is_your_role_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9e193536-c48d-4f75-8772-ffef7c2343f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>what_is_your_role_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760</value>
      <webElementGuid>f91cc3da-390a-4d8f-86bd-243f4e1dace6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-input is-placeholder</value>
      <webElementGuid>c33f67f2-0b78-46f2-abca-02d4f8e1db95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>what_is_your_role_</value>
      <webElementGuid>5f5d9159-4628-4d0a-b57f-7fc0b05ad4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Role*C-Level / VPHead / DirectorManagerConsultant / EngineerAnalystIntern / TraineeStudentOther</value>
      <webElementGuid>026f2a2e-bf7d-49b8-8eb9-2a926ffbf44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;what_is_your_role_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760&quot;)</value>
      <webElementGuid>2613884e-324d-4543-a468-65dc702903d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='what_is_your_role_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']</value>
      <webElementGuid>f2cac80b-7b80-4cc7-a9d3-f02fe0c94541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hsForm_e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']/fieldset[4]/div/div/select</value>
      <webElementGuid>43272d0d-334b-4e39-b76e-06c9afeadd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[2]</value>
      <webElementGuid>996cf0cf-537a-470c-a12f-8624e4450694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile phone number'])[1]/following::select[2]</value>
      <webElementGuid>c3da7966-f62f-4b47-a68f-0c23f88b07e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[2]</value>
      <webElementGuid>f2b45d2b-1098-45ec-91a3-a0d1dc7675c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/div/select</value>
      <webElementGuid>02ce9142-4474-4c23-bb0f-b03687b7a75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'what_is_your_role_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760' and @name = 'what_is_your_role_' and (text() = 'Role*C-Level / VPHead / DirectorManagerConsultant / EngineerAnalystIntern / TraineeStudentOther' or . = 'Role*C-Level / VPHead / DirectorManagerConsultant / EngineerAnalystIntern / TraineeStudentOther')]</value>
      <webElementGuid>e3abb48d-6571-4b4e-9b78-30c95cd3bc82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
