<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Escolher este design</name>
   <tag></tag>
   <elementGuidId>c36afac4-41b1-4236-ba6a-366b226f6074</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='chooseBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chooseBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44603d7e-2b13-4c6c-96dd-e34fe5e53751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chooseBtn</value>
      <webElementGuid>d23c898e-0f79-40dd-b6a6-5de2bd0e93c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>chooseThisTemplate()</value>
      <webElementGuid>df55d94e-01a0-4065-9c6e-e6d704367eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isLoading</value>
      <webElementGuid>fa5fdbcb-ce86-47c5-bda1-1fcca117e27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> btn btn-primary btn-md col-xs-6 select-buttons</value>
      <webElementGuid>f5496941-0619-438d-b9eb-f48311e6e8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Escolher este design 
                                </value>
      <webElementGuid>c304ec16-37a4-4d73-b2fb-d8c924f46eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chooseBtn&quot;)</value>
      <webElementGuid>289cda6f-f114-41ad-9a90-152c4fe54b9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='chooseBtn']</value>
      <webElementGuid>ecfce5ad-f009-4180-8894-ae4e737b83f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='templateDetailsModal']/div/div/div/div/div[3]/button</value>
      <webElementGuid>ed6d6201-410b-4078-9e19-c88ec4b4eede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='| + 0,00 €'])[1]/following::button[1]</value>
      <webElementGuid>2a9f27ef-bf44-45ee-b4ae-df597d4ce004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Como funciona?'])[1]/preceding::button[2]</value>
      <webElementGuid>e5458da8-6356-4ff9-943c-2f2750f7f535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diga-nos o que pretende e a nossa equipa cria um design à sua medida!'])[1]/preceding::button[2]</value>
      <webElementGuid>845abbc0-5234-4570-81e4-8337c7ba35eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Escolher este design']/parent::*</value>
      <webElementGuid>a8a8feeb-9a70-4cc2-8d02-a9f1aef3eb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/button</value>
      <webElementGuid>6304c418-f553-47bb-bb44-b3343dfd59a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'chooseBtn' and (text() = '
                                    Escolher este design 
                                ' or . = '
                                    Escolher este design 
                                ')]</value>
      <webElementGuid>9f3a4453-4d8d-4b9e-922c-965a29853b32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
