<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CheckoutCardPTUK</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4077db5d-a2b3-4273-8214-1268b3fae017</testSuiteGuid>
   <testCaseLink>
      <guid>df11d709-b645-45ee-92c3-0c27c5021319</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>'uk'</defaultValue>
         <description></description>
         <id>6e59a5ab-c421-42e3-addd-3455f4a30e1e</id>
         <masked>false</masked>
         <name>locale</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Checkout_Card</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>73237d82-774c-4e0b-aebd-9bd4b11ecd63</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/languages</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>73237d82-774c-4e0b-aebd-9bd4b11ecd63</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>locale</value>
         <variableId>6e59a5ab-c421-42e3-addd-3455f4a30e1e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
