<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PurchaseVariable</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f6e4e1cf-8dbd-4567-b643-149849ae3c4e</testSuiteGuid>
   <testCaseLink>
      <guid>8b802355-7ba1-4dde-b4c6-6cf76dc99bea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Purchase - Variable</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d52a3bb4-f0d6-42f8-bf74-70de6a96b1cb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LocaleProducts</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d52a3bb4-f0d6-42f8-bf74-70de6a96b1cb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>locale</value>
         <variableId>edd08836-5ec2-4346-a6dc-d8898bdf4de4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d52a3bb4-f0d6-42f8-bf74-70de6a96b1cb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Products</value>
         <variableId>5ea4cb3f-a2bf-4997-b675-ca9475bd6476</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
