<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apelido_Name</name>
   <tag></tag>
   <elementGuidId>6be84b19-74fc-44fc-b8d0-750b5c6e185c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1241fdd9-fdef-4b72-89fd-331af7b4c3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4c43a2cb-18e6-4420-9fe8-db16b94bcf28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9f9f150c-942a-4a72-80a2-807a1de1077c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>O campo 'Nome' tem um limite máximo de 100 caracteres.</value>
      <webElementGuid>a279b008-f4ea-4b33-b7f8-d7013f231747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d3196402-bba9-4b88-99ba-ecf5e370395c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>O campo 'Nome' não é válido.</value>
      <webElementGuid>8dd46e69-5bc1-4fb5-9537-01a48e28089c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^([a-zA-ZÀ-ÅÇ-ÏÑ-ÖÙ-Ýà-åç-ïñ-öù-ýâáäăåæëéíìîïóòôõöőøùûüúůýčďñňřšťžðœÄĂÅÁÆÉËÍÌÎÏÓÒÔÕÖŐØÙÛÜÚÝČĎÑŇŘŠßŤŽŒẞěĚĄąĆćĘęŁłŃńŚśŹźŻż\d ,;\./\\\-&amp;\(\)\[\]ºª\'\`\´\+&quot;$€\?\!@:_%#/\n]+)?$</value>
      <webElementGuid>1241a7be-2894-4990-bd72-ebd51d809b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>O campo 'Nome' é obrigatório.</value>
      <webElementGuid>90383ad2-f16e-4115-8782-dd4f898024c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>66762e46-a2eb-4fe6-a2a7-a951786ac358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>2d3307cf-c159-42b3-8c0d-39f82b564847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>callDataLayer('Click','Client_Create','createClientForm','Name')</value>
      <webElementGuid>c8dd57e7-7c4e-47a6-92bb-1f95c98d3a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c292e416-f7e6-47e1-ad87-6645a710b643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Obrigatório</value>
      <webElementGuid>c55f98c8-9404-4db1-a83f-374140688d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Name&quot;)</value>
      <webElementGuid>cb50e710-4b0d-45fb-a126-34af32697689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Name']</value>
      <webElementGuid>94c83c85-58f8-4e0d-ad0b-5c8d160350d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name-divider']/input</value>
      <webElementGuid>019a8a10-ebed-4410-a846-889c6c537108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/input</value>
      <webElementGuid>f668fa40-a854-4b93-8835-382be7d4c407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Name' and @name = 'Name' and @type = 'text' and @placeholder = 'Obrigatório']</value>
      <webElementGuid>46ec6256-9144-4e2d-8a7b-04295ce83a30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
