<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apelido_Surname</name>
   <tag></tag>
   <elementGuidId>c8d1ec1b-9f41-47d8-a202-b02f14b09a96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Surname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Surname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2c74658-dd88-49c3-b65e-3e0bf42226b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>849e055e-0d99-408f-b86a-0c60d20f7887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9a0e0c0f-1534-413f-82d6-4213cf44fb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>O campo 'Apelido' tem um limite máximo de 100 caracteres.</value>
      <webElementGuid>018a584a-0bb8-426c-a70c-9d967773c7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>8f221e85-b8a7-4c6f-ad68-7e9f75d2f157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>O campo 'Apelido' não é válido.</value>
      <webElementGuid>a8966ea3-e291-4886-be31-4ddd50fb20fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^([a-zA-ZÀ-ÅÇ-ÏÑ-ÖÙ-Ýà-åç-ïñ-öù-ýâáäăåæëéíìîïóòôõöőøùûüúůýčďñňřšťžðœÄĂÅÁÆÉËÍÌÎÏÓÒÔÕÖŐØÙÛÜÚÝČĎÑŇŘŠßŤŽŒẞěĚĄąĆćĘęŁłŃńŚśŹźŻż\d ,;\./\\\-&amp;\(\)\[\]ºª\'\`\´\+&quot;$€\?\!@:_%#/\n]+)?$</value>
      <webElementGuid>326ece0c-1060-4955-95ea-3d9541d0bc47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>5906a7ce-d908-481a-9980-3f754bec0c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>67bb2642-b499-4512-a548-949490e2de6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>callDataLayer('Click','Client_Create','createClientForm','Surname')</value>
      <webElementGuid>de4bd5da-0818-4f82-a71a-3e96f3f99a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc274981-b06a-4444-83e1-c8b74ee4ba2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Opcional</value>
      <webElementGuid>251773c7-c1c7-413c-9ff2-a319ff49ea1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Surname&quot;)</value>
      <webElementGuid>84fb4346-72ef-4f3b-a298-e4a8a4a84374</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Surname']</value>
      <webElementGuid>f15d577d-bde0-4268-b3c7-74aa823c87b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createOrEditv2']/div[2]/div[2]/input</value>
      <webElementGuid>68f986a0-2aaf-4d32-b5bb-588cf4c7390b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4075a296-bebd-4319-8f5d-0157a3b73bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Surname' and @name = 'Surname' and @type = 'text' and @placeholder = 'Opcional']</value>
      <webElementGuid>1a038d49-e124-46b4-bdc5-8c50c6e1b73f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
