<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_START PURCHASE</name>
   <tag></tag>
   <elementGuidId>1fdd4374-bc57-4763-b7bc-4069ba19c20a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#begin_purchase</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='begin_purchase']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>356f3837-eb36-4d37-a780-d4cb508aa9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>begin_purchase</value>
      <webElementGuid>a6a7e0e6-03b3-4361-bd5d-46899869b787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 begin-purchase-button</value>
      <webElementGuid>66ee732c-e94b-4237-97f1-7a8275c50e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>beginSkuPurchase()</value>
      <webElementGuid>546fbd70-62b4-4c99-accf-0f51636553bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!canInteract() || freeCVLimit</value>
      <webElementGuid>3658b549-86aa-4aff-aeb6-5c5ba0da8c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        START PURCHASE >
                    </value>
      <webElementGuid>bc3927c5-28a1-408e-9523-c954d142fb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;begin_purchase&quot;)</value>
      <webElementGuid>fa51a73f-d427-4791-b6a6-11d080544407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='begin_purchase']</value>
      <webElementGuid>cb53a1dd-c011-4ec4-a640-8bc45fcde2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calculatorController']/div/div[2]/div/div[5]</value>
      <webElementGuid>12562a08-9b22-469e-b64d-1986c6a71a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£22.85 incl VAT'])[1]/following::div[2]</value>
      <webElementGuid>f5b0255f-df0f-4222-acd2-83e92cc6b386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lowest price guaranteed.'])[1]/preceding::div[1]</value>
      <webElementGuid>b829c2f4-64dc-4243-8912-d2be8c5d8003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flyers'])[3]/preceding::div[3]</value>
      <webElementGuid>a63341da-36b7-4683-a402-4d73c521eb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='START PURCHASE >']/parent::*</value>
      <webElementGuid>f1bf8c77-b736-4a53-949a-9cc54ca27b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]</value>
      <webElementGuid>c43adf73-c2d5-4b55-9760-60624b43cbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'begin_purchase' and (text() = '
                        START PURCHASE >
                    ' or . = '
                        START PURCHASE >
                    ')]</value>
      <webElementGuid>4f249833-8b8a-4455-a630-29c1c459cf05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
