<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Entrar  Registar</name>
   <tag></tag>
   <elementGuidId>744c9465-2084-4a18-88f1-820c30205959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='login-register']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login-register</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb7913af-5443-41ee-9f4e-c2ea069c9d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-table-vertical show-upselling-modal</value>
      <webElementGuid>639db2ea-16cf-42e0-9bfa-89869f3adadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Account/Login</value>
      <webElementGuid>e7bbf4b2-4b8c-45c7-b745-98245f8641a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-register</value>
      <webElementGuid>66066afe-8cc5-437c-a9a7-b49f47a87a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Área do Cliente</value>
      <webElementGuid>d6f14f53-981d-4742-80c0-27959c8b495a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventregion</name>
      <type>Main</type>
      <value>MENU</value>
      <webElementGuid>4f5a4632-39a6-47df-a2a6-c0308d411215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventsection</name>
      <type>Main</type>
      <value>ACCOUNT</value>
      <webElementGuid>1d24fd68-27a5-4697-b6b9-acb2dab07ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventitem</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>20adbde3-2364-4467-bb0f-a8eecf2f31ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Entrar / Registar
        </value>
      <webElementGuid>aee6a7be-c8d4-4305-a92d-f18d496c9b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-register&quot;)</value>
      <webElementGuid>5680f215-84de-42b1-9519-c0dd094dd62f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='login-register']</value>
      <webElementGuid>29d223fc-56c8-4894-bef6-956a7cba3318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrap']/div[2]/div/div[3]/div/div[4]/div/div[6]/a</value>
      <webElementGuid>9bc79818-cc40-4d43-ac56-bf5cc186ff83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Entrar / Registar')]</value>
      <webElementGuid>fbc264c7-428c-4ac1-9189-a8959eddc203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mais produtos'])[1]/following::a[5]</value>
      <webElementGuid>ffe4a127-453b-4354-bd45-409e0d2d707c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[1]/following::a[6]</value>
      <webElementGuid>1b49ba04-53a4-4286-b4b8-08d8aefbd710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/preceding::a[5]</value>
      <webElementGuid>012a3349-18a0-49bd-b620-4d2f99f905a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voltar'])[1]/preceding::a[5]</value>
      <webElementGuid>375971d5-29a2-47fe-9d33-130f6c14a66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entrar / Registar']/parent::*</value>
      <webElementGuid>a4819d5b-1719-4d64-8173-b33924b8972b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Account/Login')]</value>
      <webElementGuid>ca1ab9fa-22a3-429d-b680-ae4a8aebe70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>fb74ed0b-c9e2-4b2e-b123-5f09a509647b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Account/Login' and @id = 'login-register' and @title = 'Área do Cliente' and (text() = '
            Entrar / Registar
        ' or . = '
            Entrar / Registar
        ')]</value>
      <webElementGuid>be1b32e4-6222-449e-a55c-ba7009c53705</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
