<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Criar Conta_Mobile</name>
   <tag></tag>
   <elementGuidId>11243e96-99e7-402f-9e98-d5d7c985f688</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobileRegisterSubmitBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mobileRegisterSubmitBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0b0241b1-419a-4af6-bde7-c539cb89bdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobileRegisterSubmitBtn</value>
      <webElementGuid>a8049d86-eafc-4678-ae26-d2ecd79dd91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>newbtn360 green btn-login</value>
      <webElementGuid>19af0a99-91ae-4424-87a2-3e1d26cc8dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>createNewAccountMobile()</value>
      <webElementGuid>7f2ce3a7-5af3-4437-a028-4f6db2c7fca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#mobileLogin</value>
      <webElementGuid>0820d337-11dc-40ed-ac4f-a62f335d624b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#accordionRegister</value>
      <webElementGuid>827e3e89-493a-4dd0-a232-297f96e9673d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isCreateAccountMobileDisable()</value>
      <webElementGuid>c30883fd-6c91-42ff-8311-d876747c5860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Criar Conta
                        </value>
      <webElementGuid>03f7c532-a991-4f8a-bec9-a646fedfd992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobileRegisterSubmitBtn&quot;)</value>
      <webElementGuid>b913beab-fcce-4e98-8423-a36dbe98a6d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mobileRegisterSubmitBtn']</value>
      <webElementGuid>7d687757-fc02-4815-8c77-372aa17e532c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileLogin']/div/div/div[3]/div</value>
      <webElementGuid>b150086a-34ee-42a1-beb0-30a9582e4a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[2]/following::div[3]</value>
      <webElementGuid>9789a129-aa09-47be-a22e-642cc3c76c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Política de Cookies'])[2]/following::div[3]</value>
      <webElementGuid>2f8956e9-328f-44d1-861f-e4aab1db4267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Já é cliente 360imprimir?'])[2]/preceding::div[1]</value>
      <webElementGuid>d8435d8a-5eb1-4293-b211-61df4703bb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introduza os seus dados'])[2]/preceding::div[2]</value>
      <webElementGuid>4cd179db-d84b-4f90-864d-d2b1fa90a6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div[3]/div</value>
      <webElementGuid>519514f0-284c-4391-acf5-0088f492e4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mobileRegisterSubmitBtn' and (text() = '
                            Criar Conta
                        ' or . = '
                            Criar Conta
                        ')]</value>
      <webElementGuid>20091187-799f-49a1-b07f-40973be00484</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
