<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirmar senha_ConfirmPassword</name>
   <tag></tag>
   <elementGuidId>8e9f5e84-c831-4c63-af15-c2f0fe09241f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ConfirmPasswordMobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ConfirmPasswordMobile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1dcae08-c9bb-47b2-81d0-45c027b77ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fd753a03-6b0b-4deb-b9fd-1811cd6aae6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36002ed3-523a-4bd0-bd91-7414b8e31e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto</name>
      <type>Main</type>
      <value>As passwords são diferentes.</value>
      <webElementGuid>6cfd6eb4-7d8a-42a9-b745-a2a127a4f6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto-other</name>
      <type>Main</type>
      <value>*.Password</value>
      <webElementGuid>f62317d3-92de-4a93-83f2-632c5b454bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>O campo 'Confirmar senha' é obrigatório.</value>
      <webElementGuid>837ce4bd-b89e-4579-9dd2-c413b66fbe82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConfirmPasswordMobile</value>
      <webElementGuid>ecc1f512-1521-4ac9-affc-d646c18545bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ConfirmPassword</value>
      <webElementGuid>d0830cc7-0a56-4780-ba71-1617df23066e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>callDataLayer('Click','Account_Login','Registo','ConfirmPassword')</value>
      <webElementGuid>727b7475-b87a-4bec-b4d4-64fc4813ce23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirmar senha</value>
      <webElementGuid>ae6b1ef5-03a9-4e46-a88a-c739154f5a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e8f1fd05-1dac-43a3-b9f0-603cd5a50926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConfirmPasswordMobile&quot;)</value>
      <webElementGuid>bcc44006-9368-44e6-af8d-1bab41629529</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ConfirmPasswordMobile']</value>
      <webElementGuid>213ac0f2-1c05-4b7f-9e3a-0838b70bc2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionRegister']/form/div/div[5]/input</value>
      <webElementGuid>5dea91b6-bfc0-4f32-bfd7-bdc2c44058eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/form/div/div[5]/input</value>
      <webElementGuid>c15b0983-9161-47fb-a63b-7a8b7f2b68b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ConfirmPasswordMobile' and @name = 'ConfirmPassword' and @placeholder = 'Confirmar senha' and @type = 'password']</value>
      <webElementGuid>eb212d25-35b2-4639-9c42-cd7e21d44ab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
