<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirmar Email_ConfirmUserName</name>
   <tag></tag>
   <elementGuidId>704df704-f1aa-4d44-b579-ff2b335ca90b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ConfirmUserNameMobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ConfirmUserNameMobile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f4336cc-be35-45bc-afc8-d3eb0ee9e291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3a28e686-7cef-41b2-a9e3-71d3b8721f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9cabbc55-bc1d-4fd3-b597-c46c5c7c051d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto</name>
      <type>Main</type>
      <value>Os emails são diferentes.</value>
      <webElementGuid>2042a63e-b858-46d1-8530-f111543b882c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto-other</name>
      <type>Main</type>
      <value>*.UserName</value>
      <webElementGuid>0838794b-77ef-4601-a85a-d458a7299e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>O campo 'Confirmar Email' é obrigatório.</value>
      <webElementGuid>d7f23f63-e0d9-4ef5-a730-fb965f4b86a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConfirmUserNameMobile</value>
      <webElementGuid>54d852d2-897d-4907-a3d4-a3b1443028b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ConfirmUserName</value>
      <webElementGuid>5bea7cf3-efa5-47ce-a618-897a66a232fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>callDataLayer('Click','Account_Login','Registo','ConfirmUserName')</value>
      <webElementGuid>4b45ba77-1bd7-4ece-8a28-8cf12c8694d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirmar Email</value>
      <webElementGuid>0617797e-eec4-42b1-bbf1-f7c04c1c3d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>4b027af2-22d9-4087-b990-597706eb454c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConfirmUserNameMobile&quot;)</value>
      <webElementGuid>facb37f0-16d6-4745-963d-d8958fbfbddc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ConfirmUserNameMobile']</value>
      <webElementGuid>b1f3e896-c7e5-423b-bd2f-8d1b5e1bfda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionRegister']/form/div/div[3]/input</value>
      <webElementGuid>deed2105-bb85-4784-8e41-ad14ca08c77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/form/div/div[3]/input</value>
      <webElementGuid>8998745a-ddc9-48a6-951a-23d8dc145e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ConfirmUserNameMobile' and @name = 'ConfirmUserName' and @placeholder = 'Confirmar Email' and @type = 'email']</value>
      <webElementGuid>dd231804-b93b-434b-a15b-767007229942</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
