<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Choose this design</name>
   <tag></tag>
   <elementGuidId>6aadf5ae-07ab-4ce3-86e6-4dbdcec072e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='chooseBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chooseBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>37025447-f288-4e65-96d2-0a08bd13f225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chooseBtn</value>
      <webElementGuid>236d7f0b-b017-4e8e-8432-777a809e1cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>chooseThisTemplate()</value>
      <webElementGuid>d2986e39-5ff1-48db-a9d1-73cc2f241171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isLoading</value>
      <webElementGuid>92a0bcd4-9e2a-4df1-8d02-486a49bf13b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> btn btn-primary btn-md col-xs-6 select-buttons</value>
      <webElementGuid>3c8dca43-0480-4fca-b654-d7c2c771789a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Choose this design 
                                </value>
      <webElementGuid>308c6346-d4b5-43be-927c-2bec946e56c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chooseBtn&quot;)</value>
      <webElementGuid>b2d6b916-2ffa-4b2d-ba5a-5c7480d368cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='chooseBtn']</value>
      <webElementGuid>0824b3cd-99c6-4d74-8380-01a1df70c81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='templateDetailsModal']/div/div/div/div/div[3]/button</value>
      <webElementGuid>e81312f9-329a-408f-9cc3-8e58649fef59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='| + £0.00'])[1]/following::button[1]</value>
      <webElementGuid>d995e906-a9ef-4031-b64a-997d38b04167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How does it work?'])[1]/preceding::button[2]</value>
      <webElementGuid>5e237ec0-b2be-4860-8e0b-79b7149c0f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tell us what you want and our team will create a design for you!'])[1]/preceding::button[2]</value>
      <webElementGuid>951592f2-c78d-4649-9baf-8ca15ae69371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Choose this design']/parent::*</value>
      <webElementGuid>079d8549-e9be-4224-b3f3-04d8c4a84840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div/div/div[3]/button</value>
      <webElementGuid>8c9c8630-4bd8-4339-ab2d-1ca32b1c6ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'chooseBtn' and (text() = '
                                    Choose this design 
                                ' or . = '
                                    Choose this design 
                                ')]</value>
      <webElementGuid>0e6f67d8-d47c-4b34-967c-4b7acefac504</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
