<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aceito</name>
   <tag></tag>
   <elementGuidId>8e2d1409-b594-460e-9e86-c3d2d220a22b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#onesignal-slidedown-allow-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='onesignal-slidedown-allow-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7481a23-4a90-4589-89e2-7a3216b59349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-right primary slidedown-button</value>
      <webElementGuid>56e0eef9-a281-4690-a670-c1ff2fa49d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onesignal-slidedown-allow-button</value>
      <webElementGuid>aa8ef763-e195-4c3f-bce5-a2622f083ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceito</value>
      <webElementGuid>0e4e5064-2cb1-44b7-a610-ca76c94b1b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onesignal-slidedown-allow-button&quot;)</value>
      <webElementGuid>3ca14863-e59f-4791-87df-153b5108dcfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='onesignal-slidedown-allow-button']</value>
      <webElementGuid>0fd3c0b0-a562-42c1-b7d3-9485b14279d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slidedown-footer']/button</value>
      <webElementGuid>4eb05445-3ccd-466a-99e7-0fe69976f1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gostaríamos de lhe enviar notificações com as principais novidades.'])[1]/following::button[1]</value>
      <webElementGuid>0ad33c17-ff3d-42c4-a95a-3d876f103824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'onesignal-slidedown-allow-button', '&quot;', ')')])[1]/following::button[1]</value>
      <webElementGuid>c79b1ee9-507d-4bf9-b119-c559e325dad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Não, obrigado'])[1]/preceding::button[1]</value>
      <webElementGuid>e2e6b32a-daa4-4a61-b44d-8b490debe475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aceito']/parent::*</value>
      <webElementGuid>a220260b-d3ac-47eb-8ffd-23bd0456b009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/button</value>
      <webElementGuid>71198ba2-81f8-4f35-8cae-93d213a275e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'onesignal-slidedown-allow-button' and (text() = 'Aceito' or . = 'Aceito')]</value>
      <webElementGuid>bb002817-a1fd-4747-bb98-7e99f5414d42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
