<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_START PURCHASE</name>
   <tag></tag>
   <elementGuidId>c357ab82-920c-42e5-8aff-eeacf1a93c7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='begin_purchase']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#begin_purchase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cdbe7ac8-7a7e-4ffe-a396-e453f4e4cdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>begin_purchase</value>
      <webElementGuid>f27a2e41-8bc1-48cf-a5e3-785537a66e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 begin-purchase-button</value>
      <webElementGuid>eb20f58b-e3e5-4d3f-8e7f-75d639a3950c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>beginSkuPurchase()</value>
      <webElementGuid>c0816d3e-6415-4344-8f99-b783d5abb2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!canInteract() || freeCVLimit</value>
      <webElementGuid>2163d530-cf7e-4fa7-aecb-b04b6fb79aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        START PURCHASE >
                    </value>
      <webElementGuid>17664f8a-cfe6-4d15-ad7d-6aa705bbda73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;begin_purchase&quot;)</value>
      <webElementGuid>500eea9c-73f5-4b5f-90af-ed42115a90cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='begin_purchase']</value>
      <webElementGuid>b80cc0a8-bcb1-4bf0-a56d-824c2017c182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calculatorController']/div/div[2]/div/div[5]</value>
      <webElementGuid>ff25d2e6-a0ed-4e3a-b2a6-91992c0c2b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£22.85 incl VAT'])[1]/following::div[2]</value>
      <webElementGuid>1f6e2132-e504-40d3-9979-373f23097f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lowest price guaranteed.'])[1]/preceding::div[1]</value>
      <webElementGuid>4e70e884-8f2b-464b-b600-f546d470d78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flyers'])[3]/preceding::div[3]</value>
      <webElementGuid>beb43004-88e5-4e51-b5c0-c050990135a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='START PURCHASE >']/parent::*</value>
      <webElementGuid>66d31b69-77c2-4a6c-b8fb-4bb7cda361a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]</value>
      <webElementGuid>310410ae-9ce5-4309-a02c-443e3bef2043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'begin_purchase' and (text() = '
                        START PURCHASE >
                    ' or . = '
                        START PURCHASE >
                    ')]</value>
      <webElementGuid>18e8bc5c-d434-4961-b547-103360c1086e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
