<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_INICIAR COMPRA</name>
   <tag></tag>
   <elementGuidId>2465aa86-24aa-47c4-8ec3-54a19772058c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='begin_purchase']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#begin_purchase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>640669a2-458d-4a7f-9387-e16b94e4eee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>begin_purchase</value>
      <webElementGuid>1658b144-8ab6-4bc0-928f-d80d4696b841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 begin-purchase-button</value>
      <webElementGuid>a78f756c-defe-40d7-9cc7-65ce1aaf1eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>beginSkuPurchase()</value>
      <webElementGuid>e8b75db2-a9f9-4fc4-8da4-71bd66de0e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!canInteract() || freeCVLimit</value>
      <webElementGuid>5f9dcd1e-1430-4040-9c54-b32c2a37817f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        INICIAR COMPRA >
                    </value>
      <webElementGuid>742fa3fd-4da2-46cf-a6ae-21c8541030f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;begin_purchase&quot;)</value>
      <webElementGuid>9eb7f4f6-8b75-459e-a685-be50651049d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='begin_purchase']</value>
      <webElementGuid>60d2f0fc-b8ad-41f9-ba5b-0f5d55954811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calculatorController']/div/div[2]/div/div[5]</value>
      <webElementGuid>83231af2-82fd-4509-b1a9-53a04c638969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(c/ IVA)'])[1]/following::div[2]</value>
      <webElementGuid>bd985440-8965-4a6c-bde3-dd9c0f098c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Garantia de preço mais baixo.'])[1]/preceding::div[1]</value>
      <webElementGuid>b8d0c8ab-07c4-4c89-b51a-8bf2fca05b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cartões de Visita - ps'])[3]/preceding::div[3]</value>
      <webElementGuid>995dafef-9c58-44ac-8585-1a8b149de424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INICIAR COMPRA >']/parent::*</value>
      <webElementGuid>9067b53e-4478-415d-a2dd-83fa2f81a347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]</value>
      <webElementGuid>7d4b28a5-f82f-4797-90e4-489de529566a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'begin_purchase' and (text() = '
                        INICIAR COMPRA >
                    ' or . = '
                        INICIAR COMPRA >
                    ')]</value>
      <webElementGuid>f483fd35-23ef-4c21-a8bf-a2074b255bec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
