<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Password</name>
   <tag></tag>
   <elementGuidId>ca075d74-fea3-4675-8919-8ee80c4ac562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PasswordLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PasswordLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9784023f-f9a6-4a40-9245-83c00420f879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1d2ad316-1074-4f9d-9368-43b07508baa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bda63b7e-272f-491f-9ac4-cbb24281ac2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Field 'Password' is required.</value>
      <webElementGuid>0dd25db2-6af4-409d-867d-327c00bbd869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PasswordLogin</value>
      <webElementGuid>a0afc84b-6a74-452d-aaa8-ef706ff38f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>f1c0bbd7-aff5-47c9-99c9-9efb9463be68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>callDataLayer('Click','Account_Login','Login','Password')</value>
      <webElementGuid>77c1ce47-62fb-4ac9-adbd-e4c848ea84eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>70b96046-822f-45ac-8fd9-eb604ca1b58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e144d08d-765b-4331-a27c-f929b8626e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasswordLogin&quot;)</value>
      <webElementGuid>31214710-9465-4b36-9921-3a6d62d20d67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PasswordLogin']</value>
      <webElementGuid>fdc58d83-a8e0-4dc0-b65a-794be4d2d00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseLoginForm']/form/div[2]/div[3]/input</value>
      <webElementGuid>36898ffe-a250-43bc-8840-c8e69181bdd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/form/div[2]/div[3]/input</value>
      <webElementGuid>f4f5b16d-c6b7-4476-af71-f74f3a3d6747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PasswordLogin' and @name = 'Password' and @placeholder = 'Password' and @type = 'password']</value>
      <webElementGuid>ff108ed5-75bc-40ab-9806-d98a60e71b7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
