<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Escolher este design</name>
   <tag></tag>
   <elementGuidId>dfabe13f-aa35-4814-92ac-3c476d39177f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chooseBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='chooseBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8539418a-3d71-44ff-b326-bc820c6f3ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chooseBtn</value>
      <webElementGuid>97a2b982-83f7-43b5-8aaf-e45db25c35c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>chooseThisTemplate()</value>
      <webElementGuid>4e30adab-73bc-4a59-8798-107fdfb37150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isLoading</value>
      <webElementGuid>a1253ae5-3320-4674-81ae-a61405520e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> btn btn-primary btn-md col-xs-6 select-buttons</value>
      <webElementGuid>5dde93b6-adf0-4e5f-91c2-ecd6d72594e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Escolher este design 
                                </value>
      <webElementGuid>98761c97-7b4a-4cbd-b41b-d762ab74ccd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chooseBtn&quot;)</value>
      <webElementGuid>410ee8ca-2355-40f6-b031-5b3397798d16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='chooseBtn']</value>
      <webElementGuid>7b7c11e2-3296-4da3-af40-a723c846e747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='templateDetailsModal']/div/div/div/div/div[3]/button</value>
      <webElementGuid>4a1077f1-4e0e-4922-a6f6-f99470e466d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ 1,99 €'])[8]/following::button[1]</value>
      <webElementGuid>57248289-719f-43ae-ac99-ca8648edb86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Como funciona?'])[1]/preceding::button[2]</value>
      <webElementGuid>c6331c85-db8a-4484-9550-deb0df7c09a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diga-nos o que pretende e a nossa equipa cria um design à sua medida!'])[1]/preceding::button[2]</value>
      <webElementGuid>d27459f1-0c4f-445f-9412-918fa8313e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Escolher este design']/parent::*</value>
      <webElementGuid>a2a1e198-4654-4d87-9f3e-aa5472737526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/button</value>
      <webElementGuid>24fdefcb-3685-408f-a1cb-7505360f2f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'chooseBtn' and (text() = '
                                    Escolher este design 
                                ' or . = '
                                    Escolher este design 
                                ')]</value>
      <webElementGuid>ee5cef9f-56e6-4889-bba2-8a86e5c9dfbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
