<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Siguiente</name>
   <tag></tag>
   <elementGuidId>f09b7ded-c7b0-47ad-972f-7e4bccef9fb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6a85f74c-eb20-412f-b383-0ea2c21362ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>6b27de36-272e-40b6-a4e4-88af45c95f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>newbtn360 blue btn btn-block</value>
      <webElementGuid>8931ea83-940c-4eae-9df0-7bf561bb0223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>callDataLayer('Click','Cart','Nav-Buttons','Next');CartContinue()</value>
      <webElementGuid>9e354417-91e0-46cd-9fc5-f8d554171ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{disabled : !CanContinue()}</value>
      <webElementGuid>d7eccc26-a38d-40bf-a5ae-2680925a4e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Siguiente</value>
      <webElementGuid>f593af87-8ed1-49c5-b292-3ce1315a532a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Next&quot;)</value>
      <webElementGuid>ccc2aaaa-4e72-4f4f-b266-bd28cee299b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Next']</value>
      <webElementGuid>b3d21f60-bb3c-40da-96ae-d02e6f3fe68b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[6]/div/div/div/div/div[3]/div[2]/div</value>
      <webElementGuid>70857037-7bd4-4e87-ab49-79609e097c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar más produtos'])[2]/following::div[2]</value>
      <webElementGuid>ba4ec4fe-dffb-45c8-ab38-13ef62a77507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar más produtos'])[1]/following::div[2]</value>
      <webElementGuid>9eba2afb-4370-49f1-af35-83984e7dce2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carrito'])[2]/preceding::div[1]</value>
      <webElementGuid>4c159ce9-57bd-4526-832a-7410c26b978f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El carrito está vacío'])[2]/preceding::div[2]</value>
      <webElementGuid>f74a0908-a150-47c6-aaa1-f40d2fa09a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Siguiente']/parent::*</value>
      <webElementGuid>de72af75-4cea-49b0-bf77-c7ddc501d7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div</value>
      <webElementGuid>d9c50c81-94e3-4b13-bfba-1e5667738b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Next' and (text() = 'Siguiente' or . = 'Siguiente')]</value>
      <webElementGuid>7f1410a8-da99-4c2f-84b9-fbfde0bd1bd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
