<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gr-Bretanha</name>
   <tag></tag>
   <elementGuidId>77c9f982-a44f-49f3-a078-2ab391b290d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='culture-item-default-market-5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#culture-item-default-market-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32ecd3e3-e0aa-434d-8355-c2df1adeb2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>market-label market</value>
      <webElementGuid>7f77e008-b7f2-45f0-8867-fc004b54862c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>culture-item-default-market-5</value>
      <webElementGuid>634f9f43-deb6-4077-9473-b858a2100eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://alpha.bizay.co.uk/en-gb/</value>
      <webElementGuid>fcdc9c41-f9da-4987-a957-57886e10c9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return notMakeRequest();</value>
      <webElementGuid>dc83a398-d61c-46a9-9017-7d8ce93931c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grã-Bretanha </value>
      <webElementGuid>655c9c99-dbfe-4a8f-836b-61d9313b7ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;culture-item-default-market-5&quot;)</value>
      <webElementGuid>d6e86be2-1f37-4bc1-ba2b-fbade2cb0a77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='culture-item-default-market-5']</value>
      <webElementGuid>ce4813a2-2a93-4355-8b26-b253ff74320e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='country']/a)[5]</value>
      <webElementGuid>a0d1e6bc-6d6b-4e0b-b5f6-74da0695b3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Grã-Bretanha')]</value>
      <webElementGuid>d8b6f68c-2f9f-4cb7-a4a5-8502a23c721e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ES'])[3]/following::a[1]</value>
      <webElementGuid>f52a4439-d281-4d8f-bc16-b18bbf052e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mexico'])[1]/following::a[2]</value>
      <webElementGuid>ff3f97aa-9121-46f8-bb64-d00e8e67842f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/preceding::a[1]</value>
      <webElementGuid>19370176-dddb-41dd-9164-1c1388c85504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='França'])[1]/preceding::a[2]</value>
      <webElementGuid>2763217e-59bd-41ca-b6c3-27f20fc2697b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grã-Bretanha']/parent::*</value>
      <webElementGuid>6ef2b112-bc00-4e29-88c2-fccadb6ca59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://alpha.bizay.co.uk/en-gb/')]</value>
      <webElementGuid>9c7f2bd6-f485-4888-ab52-72b3970b2ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/a</value>
      <webElementGuid>e61bba84-f639-4fd1-bd1d-4ad5f688bfe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'culture-item-default-market-5' and @href = 'https://alpha.bizay.co.uk/en-gb/' and (text() = 'Grã-Bretanha ' or . = 'Grã-Bretanha ')]</value>
      <webElementGuid>8817777d-18fb-419b-a12b-0672c5ca754c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
