<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Carrinho            (2)</name>
   <tag></tag>
   <elementGuidId>ba81f87a-2f7b-45b7-8403-3ae069eb7200</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cartAndNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cartAndNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a5e898f9-0389-46fb-af92-0941bb2cdf27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cartAndNumber</value>
      <webElementGuid>f14e2c27-e8ae-40f3-a8bb-04d9d8e480b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Carrinho
            (2)
        </value>
      <webElementGuid>22dd318d-beab-4440-bd98-f261f8fb11c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartAndNumber&quot;)</value>
      <webElementGuid>95f4a3a2-ed11-4120-8ade-a419fca4f0ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cartAndNumber']</value>
      <webElementGuid>0ea9b4b3-ee2f-4e4c-b8fc-e9399f904b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='carBtnHeader']/span</value>
      <webElementGuid>0644b795-19bf-44b8-a7a5-67429d230db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satisfação garantida'])[1]/following::span[2]</value>
      <webElementGuid>78bce686-15fa-4f9e-b02a-c81d3573deb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se conseguir encontrar um preço mais baixo, nós igualamos.'])[1]/following::span[5]</value>
      <webElementGuid>33353e99-f421-473c-9462-b9d8f2099ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mais produtos'])[1]/preceding::span[4]</value>
      <webElementGuid>8fe6292e-5fa7-4a13-89d5-981e004f11b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Carrinho']/parent::*</value>
      <webElementGuid>f4c85bd0-202c-48d9-9909-246383ab3177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>5dd396d6-cd22-4c32-8c49-cb2ce13c59d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cartAndNumber' and (text() = '
            Carrinho
            (2)
        ' or . = '
            Carrinho
            (2)
        ')]</value>
      <webElementGuid>d413a5a6-da3f-4ddb-be73-a774778ea96b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
