<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Grtis_icon-trash</name>
   <tag></tag>
   <elementGuidId>1596f674-af2b-4233-8f2f-a7b6a39c11eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[6]/div/div/div/div/div[2]/table/tbody/tr[2]/td[4]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ec9555fd-fcba-40e8-8b6d-c87afd22c9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-trash</value>
      <webElementGuid>db2d612c-e3c1-44b4-afb4-9117169e0523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 page_envelope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;hidden-xs visible-sm visible-md visible-lg&quot;]/div[2]/table[@class=&quot;table table-cart&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[4]/a[@class=&quot;btn btn-default&quot;]/i[@class=&quot;icon-trash&quot;]</value>
      <webElementGuid>828fe0a3-b4c0-4041-987d-f3015a023381</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[6]/div/div/div/div/div[2]/table/tbody/tr[2]/td[4]/a/i</value>
      <webElementGuid>3beb35cc-abce-4a34-9143-00add98b3a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>496b7485-8e02-442f-ae9a-852600e739c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
