<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sair</name>
   <tag></tag>
   <elementGuidId>6c59c5b9-935b-4660-9808-756ca0fbd7a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='logoutForm']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logoutForm > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d6adecbf-cd05-4339-a622-c59c28164506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:document.getElementById('logoutForm').submit()</value>
      <webElementGuid>e32022de-8d12-4e12-bfa9-4d1f7a0b3f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventregion</name>
      <type>Main</type>
      <value>MENU</value>
      <webElementGuid>ef455e2d-ee0f-423f-8df3-c2657d28264a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventsection</name>
      <type>Main</type>
      <value>ACCOUNT</value>
      <webElementGuid>251caa85-05e9-4392-954f-b45a6a07e95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventitem</name>
      <type>Main</type>
      <value>LOGOUT</value>
      <webElementGuid>1316288b-1af5-4321-9bc9-ea2da9ea13c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Sair
            </value>
      <webElementGuid>5b14f448-507a-4cd1-be22-1dfc4f1f84b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrap&quot;)/div[@class=&quot;hidden-xs&quot;]/div[@class=&quot;header_desktop&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row header-search&quot;]/div[@class=&quot;row no-margin-sides&quot;]/div[@class=&quot;col-xs-12 header-nav&quot;]/div[@class=&quot;col-table-2-12 nav-blue&quot;]/ul[@class=&quot;navbar-account-submenu&quot;]/li[9]/form[@id=&quot;logoutForm&quot;]/a[1]</value>
      <webElementGuid>eeb4810d-2ab2-4186-b1d1-18c467956d55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logoutForm']/a</value>
      <webElementGuid>6e4aae34-2ba6-4662-8274-819d1f5d74e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sair')]</value>
      <webElementGuid>fd9adbf6-5ec5-49e2-bcb4-ed64ddfbe0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferências'])[1]/following::a[1]</value>
      <webElementGuid>1f5e5ea0-8af7-4cbd-bce5-c7bdb61f72df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todos Ganham'])[1]/following::a[2]</value>
      <webElementGuid>01f51d80-e63f-4dbd-a862-bf8f6d71eeea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/preceding::a[5]</value>
      <webElementGuid>3edfd607-49f9-4af3-8ad8-7a39d0c8fecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voltar'])[1]/preceding::a[5]</value>
      <webElementGuid>224fa34d-8c24-4ba2-ac2c-48b7db8d76ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sair']/parent::*</value>
      <webElementGuid>8a496880-3334-47cd-87d7-5edfe23b79bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:document.getElementById('logoutForm').submit()&quot;)]</value>
      <webElementGuid>8ae03b29-28c2-4305-963f-e1ea6478aeda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/a</value>
      <webElementGuid>597925ae-23f2-4401-bbd6-3e195ed4a6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:document.getElementById(&quot; , &quot;'&quot; , &quot;logoutForm&quot; , &quot;'&quot; , &quot;).submit()&quot;) and (text() = '
                Sair
            ' or . = '
                Sair
            ')]</value>
      <webElementGuid>b082b021-cd6b-42a7-8621-1b4c3d282cb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
