<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Criar Conta_Mobile</name>
   <tag></tag>
   <elementGuidId>b146c96f-f68e-4306-a5e2-78575275a16e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobileRegisterSubmitBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mobileRegisterSubmitBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d458ceb-3c64-4e8d-875c-809fad6c8f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobileRegisterSubmitBtn</value>
      <webElementGuid>854670df-4cb2-4ca4-a6a8-b11edf7b97b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>newbtn360 green btn-login</value>
      <webElementGuid>f3f45f54-6be7-4b93-880c-c4af0b21c1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>createNewAccountMobile()</value>
      <webElementGuid>a85b49f9-bcfc-4e74-b347-9e785c04ecd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#mobileLogin</value>
      <webElementGuid>12318c6d-7674-4fe2-9e01-50a09ec4fde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#accordionRegister</value>
      <webElementGuid>c1fe3686-4c05-4399-b2ad-7cd233957369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isCreateAccountMobileDisable()</value>
      <webElementGuid>5e7c8fcd-9aa8-4c6a-be1e-0a16a75ce6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Criar Conta
                        </value>
      <webElementGuid>7d1deccd-261f-437f-8534-dcc6fbe4c9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobileRegisterSubmitBtn&quot;)</value>
      <webElementGuid>4748e315-a2ce-4f90-816a-e4ef4c4bc3a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mobileRegisterSubmitBtn']</value>
      <webElementGuid>47dc8973-9fc4-4b68-9116-4d0e89345c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileLogin']/div/div/div[3]/div</value>
      <webElementGuid>b17fc34a-3521-4727-9ddf-50d2a0c7563f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[2]/following::div[3]</value>
      <webElementGuid>e343e58d-ac1f-4dda-959a-cd2a3ee8c6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Política de Cookies'])[2]/following::div[3]</value>
      <webElementGuid>17ef0500-7ea6-403f-a473-697a5ad754ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Já é cliente 360imprimir?'])[2]/preceding::div[1]</value>
      <webElementGuid>cf832b78-5453-4e67-9ba7-2a401ded343d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introduza os seus dados'])[2]/preceding::div[2]</value>
      <webElementGuid>a3a72bdd-9c3f-40b3-8f39-989f051626b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div[3]/div</value>
      <webElementGuid>89c23a96-9511-4dae-b3eb-db8a2f3dcbb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mobileRegisterSubmitBtn' and (text() = '
                            Criar Conta
                        ' or . = '
                            Criar Conta
                        ')]</value>
      <webElementGuid>c2e473b5-cc49-4a47-8c93-b986a5b1bb69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
