<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Brasil</name>
   <tag></tag>
   <elementGuidId>248d579c-c19c-487f-ad5e-6e3d9152e5a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#culture-item-default-market-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='culture-item-default-market-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b48964d-3473-44ce-b4f3-a6f1ddbe7a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>market-label market</value>
      <webElementGuid>7d8c3c53-c3c4-43c1-852a-95697432644a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>culture-item-default-market-3</value>
      <webElementGuid>8e5bc003-136f-4c51-b320-841c61e98828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://alpha.360imprimir.com.br/pt-br/?_ga=2.201761361.1560885370.1674481601-2123411469.1674481601</value>
      <webElementGuid>e714ead5-60df-42fb-9cdb-fc855a0e4173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return notMakeRequest();</value>
      <webElementGuid>5f44c1c7-8d36-4d7d-a5e0-cffdc109ea76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brasil </value>
      <webElementGuid>7b8521dc-d6a3-4c84-86f5-fd6f4f174001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;culture-item-default-market-3&quot;)</value>
      <webElementGuid>94a5e98c-2c5a-4da2-8fb5-22ed7441b625</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='culture-item-default-market-3']</value>
      <webElementGuid>8ae273e8-dffd-42dd-a257-8c327e5513c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='country']/a)[3]</value>
      <webElementGuid>5d7d61be-adaf-43e5-aec8-98972ed22f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Brasil')]</value>
      <webElementGuid>1a0313ef-b915-48e0-ba25-c89bfbfc5bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ES'])[2]/following::a[1]</value>
      <webElementGuid>472229c4-8a11-48d0-bd9c-a3673b028fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT'])[3]/following::a[2]</value>
      <webElementGuid>167d1762-0df0-4b07-b7ff-e227059ce57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT'])[4]/preceding::a[1]</value>
      <webElementGuid>869f355e-d7a8-4c8a-a82a-ae0f0092c74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mexico'])[1]/preceding::a[2]</value>
      <webElementGuid>a9037d00-da12-4f71-b9fa-8a5a8778ede9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Brasil']/parent::*</value>
      <webElementGuid>7a04ac9b-1094-4c9f-93ee-f74b044249da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://alpha.360imprimir.com.br/pt-br/?_ga=2.201761361.1560885370.1674481601-2123411469.1674481601')]</value>
      <webElementGuid>9b8fb52d-f51f-46b6-8ea1-fe40ea67f9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/a</value>
      <webElementGuid>4838f853-9adc-4a1d-b8f3-4cb5b32f9821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'culture-item-default-market-3' and @href = 'https://alpha.360imprimir.com.br/pt-br/?_ga=2.201761361.1560885370.1674481601-2123411469.1674481601' and (text() = 'Brasil ' or . = 'Brasil ')]</value>
      <webElementGuid>8e404079-6b46-4021-be41-a56f1a6197d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
