<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Grtis_icon-trash</name>
   <tag></tag>
   <elementGuidId>8fb102c9-6312-4e8e-82d8-424ecdf707f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[6]/div/div/div/div/div[2]/table/tbody/tr[2]/td[4]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>362ea509-4686-4658-814b-802a1d98b24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-trash</value>
      <webElementGuid>3d04ded0-6943-4543-a85a-8c90abd3f1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 page_envelope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;hidden-xs visible-sm visible-md visible-lg&quot;]/div[2]/table[@class=&quot;table table-cart&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[4]/a[@class=&quot;btn btn-default&quot;]/i[@class=&quot;icon-trash&quot;]</value>
      <webElementGuid>37d3a3ed-7403-447c-9101-e582914de208</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[6]/div/div/div/div/div[2]/table/tbody/tr[2]/td[4]/a/i</value>
      <webElementGuid>5b57f93c-ea4d-4165-a0f4-2fe01151f811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>438874b2-e01d-444e-9ee3-3178fb117e21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
