<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gostaramos de lhe enviar notificaes com_cbb438</name>
   <tag></tag>
   <elementGuidId>a35b50b8-480e-4c6e-8a2f-74e5e9e14bde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#onesignal-slidedown-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='onesignal-slidedown-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98103cf4-d3e6-4308-90b1-13a391be3cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onesignal-slidedown-container</value>
      <webElementGuid>41fde27f-6e7a-4c26-be8b-862b0acb1e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onesignal-slidedown-container onesignal-reset slide-down</value>
      <webElementGuid>f0bd41df-b88a-47ad-85d7-5cd17526bd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gostaríamos de lhe enviar notificações com as principais novidades.AceitoNão, obrigado</value>
      <webElementGuid>8541b04f-5380-441b-b2ba-710f125f5a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onesignal-slidedown-container&quot;)</value>
      <webElementGuid>35b50a08-9f44-4cf1-a033-754565cf0aa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='onesignal-slidedown-container']</value>
      <webElementGuid>655efa31-b3fd-4189-96d9-de3d69b9d5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'onesignal-slidedown-container', '&quot;', ')')])[1]/following::div[1]</value>
      <webElementGuid>1eb7212b-ed16-402a-8fb0-c7b4684acda9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Não voltar a mostrar'])[2]/following::div[5]</value>
      <webElementGuid>8145a494-810a-45d4-ad75-a95576f628aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]</value>
      <webElementGuid>bcf07930-a77e-4c46-813f-67a8728ab2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'onesignal-slidedown-container' and (text() = 'Gostaríamos de lhe enviar notificações com as principais novidades.AceitoNão, obrigado' or . = 'Gostaríamos de lhe enviar notificações com as principais novidades.AceitoNão, obrigado')]</value>
      <webElementGuid>840b8419-5519-49f9-bdc2-b18cd0193852</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
