<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Carrinho            (1)</name>
   <tag></tag>
   <elementGuidId>15821d3e-9aab-400a-a6a9-422a1b0e1be6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cartAndNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cartAndNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b5d3f2cd-97a9-4c7d-8549-9bad286a8ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cartAndNumber</value>
      <webElementGuid>80f468e5-643c-4461-8454-034bf31ec78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Carrinho
            (1)
        </value>
      <webElementGuid>e05b38b3-ccd9-4f65-8057-7a1100b083a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartAndNumber&quot;)</value>
      <webElementGuid>e624d1f6-1fe0-4ac8-a8d6-a3b65701cfad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cartAndNumber']</value>
      <webElementGuid>42e53eb0-acf4-401a-9216-ae9d0eace64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='carBtnHeader']/span</value>
      <webElementGuid>f3ec46b8-ab3e-4a9c-a468-16a761227d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satisfação garantida'])[1]/following::span[2]</value>
      <webElementGuid>d7a7dd0f-43f1-4135-b9ed-08ea552f95ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se conseguir encontrar um preço mais baixo, nós igualamos.'])[1]/following::span[5]</value>
      <webElementGuid>344de939-c347-4351-968e-7ca0c7f0b0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mais produtos'])[1]/preceding::span[4]</value>
      <webElementGuid>8d68fcc6-8dc0-47d0-942f-be84d034877a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Carrinho']/parent::*</value>
      <webElementGuid>0464415a-8d25-4db3-bc10-79c1f0087f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>2521e2fb-02e2-4dc8-98ec-46b525466279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cartAndNumber' and (text() = '
            Carrinho
            (1)
        ' or . = '
            Carrinho
            (1)
        ')]</value>
      <webElementGuid>6d78b767-1fb9-4085-8992-d6de7d26fe25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
