<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Basket            (1)</name>
   <tag></tag>
   <elementGuidId>246f0b1e-7870-4f3e-85c7-386316c813fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cartAndNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cartAndNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6b613f4e-a172-4b75-9f03-4cd5d616655f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cartAndNumber</value>
      <webElementGuid>9682f1b8-25ce-4360-81d5-0de9b1c29020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Basket
            (1)
        </value>
      <webElementGuid>0eb6f051-690a-4bbd-aa66-e6562d5d0e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartAndNumber&quot;)</value>
      <webElementGuid>6efa10d3-f4a5-45c7-bd40-c4ab22dd1663</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cartAndNumber']</value>
      <webElementGuid>74182785-8802-456b-894f-b8ccc12fe76e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='carBtnHeader']/span</value>
      <webElementGuid>d938d656-2174-41d9-8b21-aa366088afde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satisfaction Guaranteed'])[1]/following::span[2]</value>
      <webElementGuid>92e41b5d-b5a7-4f97-ba70-e8f11f26a0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('If you find a lower price, we', &quot;'&quot;, 'll match the price.')])[1]/following::span[5]</value>
      <webElementGuid>04f2f409-cb18-4719-b0b7-618b02708b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other products'])[1]/preceding::span[4]</value>
      <webElementGuid>a1648746-c32e-42db-b169-b6067ad7e724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Basket']/parent::*</value>
      <webElementGuid>665ae3d2-768d-4b85-b69f-158dea39230d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>9a07fcbd-d84a-43ff-8aca-61714f1a7d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cartAndNumber' and (text() = '
            Basket
            (1)
        ' or . = '
            Basket
            (1)
        ')]</value>
      <webElementGuid>b4be85a6-ed46-4162-b9dc-86c3dfab035e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
