<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sair</name>
   <tag></tag>
   <elementGuidId>ba468710-c9e4-4462-b876-987f2ab4c95c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logoutForm > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='logoutForm']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ff4ee7a9-3f13-4f2e-a1fe-a6261f148f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:document.getElementById('logoutForm').submit()</value>
      <webElementGuid>f032b38f-e9a7-4cc6-98fc-3729be469b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventregion</name>
      <type>Main</type>
      <value>MENU</value>
      <webElementGuid>8ee6c175-f78c-428e-a1e8-17464002ea92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventsection</name>
      <type>Main</type>
      <value>ACCOUNT</value>
      <webElementGuid>2c57c63b-47a6-4691-a988-39ceb030834f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventitem</name>
      <type>Main</type>
      <value>LOGOUT</value>
      <webElementGuid>3052a4ba-9ddd-4423-bd9d-63f75d5e8e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Sair
            </value>
      <webElementGuid>de3dd03d-d1ba-4f59-aa96-aea27c26c56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrap&quot;)/div[@class=&quot;hidden-xs&quot;]/div[@class=&quot;header_desktop&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row header-search&quot;]/div[@class=&quot;row no-margin-sides&quot;]/div[@class=&quot;col-xs-12 header-nav&quot;]/div[@class=&quot;col-table-2-12 nav-blue&quot;]/ul[@class=&quot;navbar-account-submenu&quot;]/li[8]/form[@id=&quot;logoutForm&quot;]/a[1]</value>
      <webElementGuid>66869027-f59d-4fff-a6d7-8b08ebc23564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logoutForm']/a</value>
      <webElementGuid>502d08ab-b903-42bb-86f5-3a05409cee60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sair')]</value>
      <webElementGuid>35dbe7a0-c14d-4a01-901d-69edb61aa0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferências'])[1]/following::a[1]</value>
      <webElementGuid>82fe3cee-d9fb-4ee7-8ef4-893363d51af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todos Ganham'])[1]/following::a[2]</value>
      <webElementGuid>90a2f072-2324-4e20-9365-2c97af40d86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/preceding::a[5]</value>
      <webElementGuid>b109dec1-0b50-4ed5-bc1f-0cb8b77dc76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voltar'])[1]/preceding::a[5]</value>
      <webElementGuid>cd061ad1-db40-4298-a6f4-fe1cdf219141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sair']/parent::*</value>
      <webElementGuid>83ac6d0d-25c4-4adf-8213-60cca6e3d882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:document.getElementById('logoutForm').submit()&quot;)]</value>
      <webElementGuid>149fadbd-b04f-4e21-95a5-ed8ad4e3cbb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/a</value>
      <webElementGuid>55d587f4-4e17-4998-a441-b3b089c9f06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:document.getElementById(&quot; , &quot;'&quot; , &quot;logoutForm&quot; , &quot;'&quot; , &quot;).submit()&quot;) and (text() = '
                Sair
            ' or . = '
                Sair
            ')]</value>
      <webElementGuid>fde6ae62-46c7-435c-891d-d54d5b814361</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
