<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_START PURCHASE</name>
   <tag></tag>
   <elementGuidId>eb582a2b-82d4-4083-bf1d-6da9d0acd2aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='begin_purchase']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#begin_purchase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>51c38ce2-ce76-4410-95fa-418a80305ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>begin_purchase</value>
      <webElementGuid>45000fbe-3a74-47ce-8158-d87fa37d06de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 begin-purchase-button</value>
      <webElementGuid>1a5f9c7b-31e1-47d7-8dfa-40300541f00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>beginSkuPurchase()</value>
      <webElementGuid>57315e3d-c1d9-4518-9a73-930657e38aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!canInteract() || freeCVLimit</value>
      <webElementGuid>158fa885-ab34-4899-a1fc-55a731c91c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        START PURCHASE >
                    </value>
      <webElementGuid>26be4eaa-f0a3-4265-a8bc-af46c34bf215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;begin_purchase&quot;)</value>
      <webElementGuid>3917333d-1835-4d17-85e3-769efa4e9252</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='begin_purchase']</value>
      <webElementGuid>72cb43f0-b3f7-47c0-ad3c-fb123dec575a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calculatorController']/div/div[2]/div/div[5]</value>
      <webElementGuid>8d5db51d-3a5f-4d90-a52c-4e0ba93476f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£22.85 incl VAT'])[1]/following::div[2]</value>
      <webElementGuid>d7961f9f-efe2-45bd-8334-a8d176b056a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lowest price guaranteed.'])[1]/preceding::div[1]</value>
      <webElementGuid>6115c866-7f4e-48ea-86fc-0ef3281c3c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flyers'])[3]/preceding::div[3]</value>
      <webElementGuid>68fcad48-03d9-40b0-9b57-688d76b81e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='START PURCHASE >']/parent::*</value>
      <webElementGuid>df2529f9-6064-4a93-9053-3211cc9212c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]</value>
      <webElementGuid>71beb6de-36ce-4b68-a7b0-5ff98e2908ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'begin_purchase' and (text() = '
                        START PURCHASE >
                    ' or . = '
                        START PURCHASE >
                    ')]</value>
      <webElementGuid>162d87e5-90b1-4d8d-9aca-82db1f349085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
