<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Espanha</name>
   <tag></tag>
   <elementGuidId>710b5052-f06d-4669-8b72-73c6d98cddb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='culture-item-default-market-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#culture-item-default-market-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79e0d247-2c93-49cf-b4c2-269a325c67d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>market-label market</value>
      <webElementGuid>f18c1b3c-21dd-4193-9d7d-468fa3558bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>culture-item-default-market-2</value>
      <webElementGuid>a0fe0359-bcba-47f4-91ad-b50a79e1d1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://alpha.360imprimir.es/es-es/?_ga=2.160230654.2102273434.1673898410-56767670.1673898410</value>
      <webElementGuid>d99c34a7-5830-488c-bbf7-ec16f1ded9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return notMakeRequest();</value>
      <webElementGuid>144f72f3-3363-4256-8030-70c4084bcccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Espanha </value>
      <webElementGuid>186b365d-f522-4df4-8d8e-297f74884c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;culture-item-default-market-2&quot;)</value>
      <webElementGuid>ce8100b4-3dea-4082-bf9c-e81e00ed623f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='culture-item-default-market-2']</value>
      <webElementGuid>23e87efe-1d52-44ac-8146-a2f32faf88ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='country']/a)[2]</value>
      <webElementGuid>cece6157-0a90-425d-aad0-598910427c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Espanha')]</value>
      <webElementGuid>7a58f02e-0f2d-46ca-8265-6a69aae8c27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT'])[2]/following::a[1]</value>
      <webElementGuid>e4133ef6-c8d7-48f2-b09b-ae00f8f97721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ES'])[1]/following::a[2]</value>
      <webElementGuid>19d1e9f9-0dbe-47b7-9720-eeaa81dbbb30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT'])[3]/preceding::a[1]</value>
      <webElementGuid>03298f58-9558-48c7-b7f6-aa665ea74fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ES'])[2]/preceding::a[2]</value>
      <webElementGuid>8a9691a0-004a-44a8-8bf8-97d61e654919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Espanha']/parent::*</value>
      <webElementGuid>394c387b-381f-45f5-9b39-5006c7f6c6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://alpha.360imprimir.es/es-es/?_ga=2.160230654.2102273434.1673898410-56767670.1673898410')]</value>
      <webElementGuid>6a9b11be-0569-480e-9e5d-4ff07da93607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a</value>
      <webElementGuid>8d9d5ea1-2bc0-4a7d-92c4-59897d212275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'culture-item-default-market-2' and @href = 'https://alpha.360imprimir.es/es-es/?_ga=2.160230654.2102273434.1673898410-56767670.1673898410' and (text() = 'Espanha ' or . = 'Espanha ')]</value>
      <webElementGuid>cd47a102-2a78-4ccc-880b-b2c527573660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
