<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Stickers</name>
   <tag></tag>
   <elementGuidId>0cf9ee35-0034-42b6-8ee9-64361638c431</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='headeritem-2']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headeritem-2 > p.ellip.ellip-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>32708ff1-a89f-45af-9f72-3ea3533a0122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ellip ellip-2</value>
      <webElementGuid>d9d96d79-c87c-45ee-a793-51de8b4f806f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stickers</value>
      <webElementGuid>8f13a009-4994-477f-9029-ee431e083495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headeritem-2&quot;)/p[@class=&quot;ellip ellip-2&quot;]</value>
      <webElementGuid>37b0cbec-2488-455a-8064-107684333e5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='headeritem-2']/p</value>
      <webElementGuid>3aad6253-cf43-4bf8-a351-e106573e6e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other products'])[1]/following::p[302]</value>
      <webElementGuid>c05a710b-3606-40cd-be09-7cb8f213c9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2)'])[1]/following::p[302]</value>
      <webElementGuid>7fe4a1e5-c1a8-42a0-8a23-095f905ae3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Information'])[1]/preceding::p[2]</value>
      <webElementGuid>d9f136f5-b41e-4cd6-9d73-d82b37e7b491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Addresses'])[1]/preceding::p[2]</value>
      <webElementGuid>5e642532-feec-49e0-aaa9-8096290b7d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/p</value>
      <webElementGuid>8a87aae0-c169-461d-b63a-ce8c8f120b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Stickers' or . = 'Stickers')]</value>
      <webElementGuid>efbc66ea-0401-4ab8-8d5d-d7921d6597cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
