<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Password</name>
   <tag></tag>
   <elementGuidId>7d27404c-395c-4261-8dd2-fdd7bbf34c70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PasswordLogin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PasswordLogin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5013c2d1-7d3f-4902-bc19-3665fec9f787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>855740cb-54a4-44e9-9dc8-6ab0e203f115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c379a87b-11d0-4899-b712-c90422cd010f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>O campo 'Senha' é obrigatório.</value>
      <webElementGuid>ee5988b4-9710-4bbe-97e7-e34c32b2c642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PasswordLogin</value>
      <webElementGuid>a8d0be50-d590-4c8b-9d8a-9e0e0c2d868b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>045a6215-9748-47be-b17b-166ee7ae883d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>callDataLayer('Click','Account_Login','Login','Password')</value>
      <webElementGuid>7cdae765-ea86-488e-818c-a70c2e346bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Senha</value>
      <webElementGuid>6f4a67a0-9853-4b8f-8467-685ea7b11353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2cd9e5df-71d3-408e-9932-e3d6b0b475b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasswordLogin&quot;)</value>
      <webElementGuid>6195d350-3f13-4633-8fc5-786ef279a608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PasswordLogin']</value>
      <webElementGuid>53cab268-8a24-405f-a4fa-a38262aae170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseLoginForm']/form/div[2]/div[3]/input</value>
      <webElementGuid>9015adb2-7bcd-47d8-98b9-70bf529f5e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/form/div[2]/div[3]/input</value>
      <webElementGuid>7b34d8e8-01e0-4969-a7c5-8752185155e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PasswordLogin' and @name = 'Password' and @placeholder = 'Senha' and @type = 'password']</value>
      <webElementGuid>36faf600-a8a0-4354-9d39-8914e4faf6e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
