<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gr-Bretanha</name>
   <tag></tag>
   <elementGuidId>f1232ebd-03af-4f05-9e0d-68fd3e2bc55d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#culture-item-default-market-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='culture-item-default-market-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e7f8068b-42f3-4573-968f-68ecb9031516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>market-label market</value>
      <webElementGuid>7f926337-748e-4645-b49b-4ba7a8e8eac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>culture-item-default-market-5</value>
      <webElementGuid>3bac0e33-29f1-487d-a9a1-e2852074f827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://alpha.bizay.co.uk/en-gb/</value>
      <webElementGuid>2fb9e2ba-8f98-43b0-a3fa-34f8920f3a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return notMakeRequest();</value>
      <webElementGuid>0f8f13b8-7f83-4217-9341-e5d0f48da286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grã-Bretanha </value>
      <webElementGuid>9a54ea6f-bd30-4ed7-a604-31e35e12a8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;culture-item-default-market-5&quot;)</value>
      <webElementGuid>d047029e-e5d3-49f2-8958-633cfe824950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='culture-item-default-market-5']</value>
      <webElementGuid>d2ccbcc7-a21e-4e93-9b4c-233bad96a833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='country']/a)[5]</value>
      <webElementGuid>ac92ca9a-042c-4a09-83cc-8a69cb304278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Grã-Bretanha')]</value>
      <webElementGuid>e30f185a-c625-42da-955c-088c01059687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ES'])[3]/following::a[1]</value>
      <webElementGuid>f25eaf6d-df9a-409a-a0ec-f0b8b0bc97fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mexico'])[1]/following::a[2]</value>
      <webElementGuid>6244f38e-49ea-4f4c-9e06-dd9f641ca4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/preceding::a[1]</value>
      <webElementGuid>b3386b38-2506-41da-89e9-846c1b76ca06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='França'])[1]/preceding::a[2]</value>
      <webElementGuid>db9361f9-7b27-4194-92a8-7eec509f1e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grã-Bretanha']/parent::*</value>
      <webElementGuid>089557df-831d-4238-ab90-a3fef460ae59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://alpha.bizay.co.uk/en-gb/')]</value>
      <webElementGuid>a75cf303-16fb-4d04-8489-81540b8a01fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/a</value>
      <webElementGuid>01247f0c-deed-4841-a7c4-3825084945f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'culture-item-default-market-5' and @href = 'https://alpha.bizay.co.uk/en-gb/' and (text() = 'Grã-Bretanha ' or . = 'Grã-Bretanha ')]</value>
      <webElementGuid>6c494442-2143-429a-9081-036dee8a4e6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
