<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_INICIAR COMPRA</name>
   <tag></tag>
   <elementGuidId>26f82dc8-0e60-463d-a21c-772446279e6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#begin_purchase</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='begin_purchase']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8fa526cc-c90a-4f0f-9888-49173bf76057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>begin_purchase</value>
      <webElementGuid>969b17ac-e1db-414c-8c85-e9899e8a30bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 begin-purchase-button</value>
      <webElementGuid>e4de2311-0e5c-496f-bdd1-4a3889a43ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>beginSkuPurchase()</value>
      <webElementGuid>1e0867c8-2a50-49b3-9103-2a89758c582f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!canInteract() || freeCVLimit</value>
      <webElementGuid>ee8fc062-5c8a-4c00-88a8-968469e9c1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        INICIAR COMPRA >
                    </value>
      <webElementGuid>d0771126-c760-4d5b-b8a1-4c3b6beeecab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;begin_purchase&quot;)</value>
      <webElementGuid>887d69d6-a8e9-434c-a157-f346f4786be3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='begin_purchase']</value>
      <webElementGuid>3d3ebaaf-a698-4688-bce9-ddc5aad2b930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calculatorController']/div/div[2]/div/div[5]</value>
      <webElementGuid>f65082f6-8049-428f-b1cd-f1c1969c14a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(c/ IVA)'])[1]/following::div[2]</value>
      <webElementGuid>61e8f65e-0a13-4a3c-9db5-ed863e703187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Garantia de preço mais baixo.'])[1]/preceding::div[1]</value>
      <webElementGuid>88094f91-9161-4fb7-b142-ee35b65024a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cartões de Visita - ps'])[3]/preceding::div[3]</value>
      <webElementGuid>4222a1fa-c12c-4c5d-bf2b-852a58d7787e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INICIAR COMPRA >']/parent::*</value>
      <webElementGuid>08a17219-f4f7-4ba6-adac-b3597db2ea2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]</value>
      <webElementGuid>9b3a8591-7485-49b5-88d5-a81670387c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'begin_purchase' and (text() = '
                        INICIAR COMPRA >
                    ' or . = '
                        INICIAR COMPRA >
                    ')]</value>
      <webElementGuid>734c3544-2a40-413d-8310-33d51a5e6299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
