<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please complete this required field_lastname</name>
   <tag></tag>
   <elementGuidId>a5ce3698-d234-4cd3-8e57-df02e99ee204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lastname-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lastname-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>912fec42-1e9a-4373-9b95-18d8b53ea5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lastname-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760</value>
      <webElementGuid>59ff4222-5f2b-4bcd-b7e5-f56a8e6bc3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>c490a565-c3ef-4951-acce-fdbacc70986a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last name*</value>
      <webElementGuid>ca39e066-86bb-4052-89d3-baa77427e1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9854a674-858a-435e-a0e4-f1ac63673071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-input</value>
      <webElementGuid>7a8dd89f-cdd8-4df1-86e1-f1fb18339483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7c04134-634c-4741-8c90-0ecf479cd652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>family-name</value>
      <webElementGuid>a5cac37a-5de4-42ad-ae72-f687cfdcd067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lastname-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760&quot;)</value>
      <webElementGuid>9a6baaed-a357-44d4-9a5c-e4226f22420b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lastname-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']</value>
      <webElementGuid>b22aa3b1-f1cc-42bc-b74c-35d6252f16c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hsForm_e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']/fieldset/div[2]/div/input</value>
      <webElementGuid>98914d42-f4b9-4676-acdd-8051a4f91263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>f4201ffa-f0de-4865-acda-e47340d716e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lastname-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760' and @name = 'lastname' and @placeholder = 'Last name*' and @type = 'text']</value>
      <webElementGuid>8c3a304d-76a6-4ba8-b18a-d418ae27ca24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
