<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DepartmentBoard  ExecutiveMarketingSalesIT - DevelopmentIT - Architect  InfrastructureIT</name>
   <tag></tag>
   <elementGuidId>0ec4a5af-2e55-40e6-b318-b795ee838c1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#what_is_your_department_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='what_is_your_department_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c06be483-c365-4502-8bbc-effd32b88c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>what_is_your_department_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760</value>
      <webElementGuid>ea2ba939-69ee-4d5f-a33e-42bdecd70694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-input is-placeholder</value>
      <webElementGuid>1546418a-1765-4241-b28d-2f031b66a88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>what_is_your_department_</value>
      <webElementGuid>cc219710-e094-4207-a856-fff880d13508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Department*Board / ExecutiveMarketingSalesIT - DevelopmentIT - Architect / InfrastructureIT - DatabaseIT - Data ScienceIT - Project ManagerCustomer ServiceHuman ResourcesOperationsFinancial / ProcurementOther</value>
      <webElementGuid>6c8f8521-f673-45c6-a43d-06d686e26ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;what_is_your_department_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760&quot;)</value>
      <webElementGuid>d5b92b83-b046-4fd5-8a38-c75ecd1dac43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='what_is_your_department_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']</value>
      <webElementGuid>0e046f6a-2254-455c-8423-5986ae678ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hsForm_e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']/fieldset[4]/div[2]/div/select</value>
      <webElementGuid>e8b5482c-7a85-4aa7-b53f-61841277510f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select an option from the dropdown menu.'])[1]/following::select[1]</value>
      <webElementGuid>511c89e5-222b-44d1-85ff-52f15acf7868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please complete this required field.'])[5]/following::select[2]</value>
      <webElementGuid>9c29831c-cc7c-426a-a9ad-430303229e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>41316b09-a51d-47e2-a595-6c8c54408d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>b149aa52-f9c6-49fd-a26d-5796f68d7294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'what_is_your_department_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760' and @name = 'what_is_your_department_' and (text() = 'Department*Board / ExecutiveMarketingSalesIT - DevelopmentIT - Architect / InfrastructureIT - DatabaseIT - Data ScienceIT - Project ManagerCustomer ServiceHuman ResourcesOperationsFinancial / ProcurementOther' or . = 'Department*Board / ExecutiveMarketingSalesIT - DevelopmentIT - Architect / InfrastructureIT - DatabaseIT - Data ScienceIT - Project ManagerCustomer ServiceHuman ResourcesOperationsFinancial / ProcurementOther')]</value>
      <webElementGuid>89c441f7-389d-4971-baa0-ea385574fcdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
