<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_RoleC-Level  VPHead  DirectorManagerConsultant  EngineerAnalystIntern  TraineeStudentOther</name>
   <tag></tag>
   <elementGuidId>54afe1d1-2374-4bd4-aa6e-a743332ca596</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#what_is_your_role_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='what_is_your_role_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ed57733e-fde0-4291-aadf-226fa3699bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>what_is_your_role_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760</value>
      <webElementGuid>3b52cc50-956f-4078-bee6-0bec8599fd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-input is-placeholder</value>
      <webElementGuid>48c432ea-84ed-484d-9990-ac0b8427ba0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>what_is_your_role_</value>
      <webElementGuid>2f1afd7b-a4f0-405a-b92b-80099b1833eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Role*C-Level / VPHead / DirectorManagerConsultant / EngineerAnalystIntern / TraineeStudentOther</value>
      <webElementGuid>c980fa1d-6890-45bc-b07e-e4f6542998c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;what_is_your_role_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760&quot;)</value>
      <webElementGuid>32d1e57c-b8b9-4abf-b07d-85eb7db792bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='what_is_your_role_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']</value>
      <webElementGuid>0dcd7f8d-8b63-43de-9bdb-3caa41eec029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hsForm_e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760']/fieldset[4]/div/div/select</value>
      <webElementGuid>5addecf0-7343-4c23-b483-fcaea8bc820c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please complete this required field.'])[5]/following::select[1]</value>
      <webElementGuid>c3858a9d-2f46-4f1b-9326-dc75ff55a3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[2]</value>
      <webElementGuid>56f6e326-d1f8-4cff-8938-5ba6d3d182e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[2]</value>
      <webElementGuid>8185f268-a0e9-42aa-9096-9a430d5492f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/div/select</value>
      <webElementGuid>42d6b679-f264-4c9e-a571-b8d486b28865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'what_is_your_role_-e08a4a3c-4d83-4f4c-aa78-28a39bd931df_9760' and @name = 'what_is_your_role_' and (text() = 'Role*C-Level / VPHead / DirectorManagerConsultant / EngineerAnalystIntern / TraineeStudentOther' or . = 'Role*C-Level / VPHead / DirectorManagerConsultant / EngineerAnalystIntern / TraineeStudentOther')]</value>
      <webElementGuid>00288a7e-a7b7-4535-8e5f-87b3ca77591b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
