<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fechar</name>
   <tag></tag>
   <elementGuidId>92933531-0b57-4a66-aa5d-f4b3e9c44b95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.introjs-skipbutton.btn360.btn360mini.btn-red.btn-tour</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Fechar')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a5122d3a-0208-4e9b-aff3-7d8f43806b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>introjs-skipbutton btn360 btn360mini btn-red btn-tour</value>
      <webElementGuid>cc0828ea-01da-47d6-9c29-355f8dcdd0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>4ed99c8e-a5c1-41f9-8fee-65b43eda6666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fechar</value>
      <webElementGuid>a47714b5-d34a-4382-8056-ceb026f64ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[@class=&quot;introjs-tooltipReferenceLayer&quot;]/div[@class=&quot;introjs-tooltip&quot;]/div[@class=&quot;introjs-tooltipbuttons&quot;]/a[@class=&quot;introjs-skipbutton btn360 btn360mini btn-red btn-tour&quot;]</value>
      <webElementGuid>c67b8658-f843-4019-b548-124c2f552ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Fechar')])[2]</value>
      <webElementGuid>a007f4a2-6fad-4441-9f6b-13a135ea8030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escolha o que quer editar'])[1]/following::a[14]</value>
      <webElementGuid>251ca483-9e87-4472-8b83-15bf4e7359a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Não, obrigado'])[1]/following::a[14]</value>
      <webElementGuid>775f4a89-302a-445a-b1ba-5b0b0215236f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::a[1]</value>
      <webElementGuid>fb1ab8ce-6cb8-481d-8f61-26c74fddc6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voltar'])[2]/preceding::a[1]</value>
      <webElementGuid>6cf57072-acf9-44e0-b47f-35753d4ab4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[16]</value>
      <webElementGuid>60aee4d3-75f6-4ab0-a5bf-cce57d2295f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[5]/a</value>
      <webElementGuid>9b37420a-4eaf-4723-9c0d-1b3048888a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Fechar' or . = 'Fechar')]</value>
      <webElementGuid>0c58996d-d57c-4dbe-8138-34a2d422447f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
