<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Escolher este design</name>
   <tag></tag>
   <elementGuidId>3e6a06af-2180-4a5c-a96c-e88e26761679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='chooseBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chooseBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79bad723-79cd-4b44-9958-a99c9fbd4c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chooseBtn</value>
      <webElementGuid>961a3ea0-c10d-4629-b8a3-4747b0dfe2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>chooseThisTemplate()</value>
      <webElementGuid>e546b5c9-7f0c-4726-b9d9-3f71a0e46047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isLoading</value>
      <webElementGuid>5a3a559a-708c-4b6a-8b0f-98a7a09fa3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> btn btn-primary btn-md col-xs-6 select-buttons</value>
      <webElementGuid>c51f4bc8-802f-40ab-a52f-7681c74ab2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Escolher este design 
                                </value>
      <webElementGuid>9c99a571-51b2-479e-80e6-55bffa05aa07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chooseBtn&quot;)</value>
      <webElementGuid>64952d6a-0bd9-4788-bd54-e0e359bad658</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='chooseBtn']</value>
      <webElementGuid>3d1a028d-4a33-40f4-9d09-f7c8de4055ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='templateDetailsModal']/div/div/div/div/div[3]/button</value>
      <webElementGuid>9afbe16b-02ea-477c-bfd7-4d3a9b953e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='| + 0,00 €'])[1]/following::button[1]</value>
      <webElementGuid>fd338313-4c81-4324-892f-9058437d8bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Como funciona?'])[1]/preceding::button[2]</value>
      <webElementGuid>c116cf1a-c9cc-449f-b331-2fd58ce0943f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diga-nos o que pretende e a nossa equipa cria um design à sua medida!'])[1]/preceding::button[2]</value>
      <webElementGuid>8a5a05e6-b647-4e1f-be61-1765540db20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Escolher este design']/parent::*</value>
      <webElementGuid>7e9a1b67-6948-4569-a605-7834fe103e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/button</value>
      <webElementGuid>2adf58e8-a142-43fc-aa11-25842935d3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'chooseBtn' and (text() = '
                                    Escolher este design 
                                ' or . = '
                                    Escolher este design 
                                ')]</value>
      <webElementGuid>32a3b697-cbc0-4a3f-9ef2-d6cad36f2b3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
