<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Next</name>
   <tag></tag>
   <elementGuidId>08205e3c-6bb1-451d-a954-f275b6359e6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a75a10bb-c3af-4b2f-b3ea-d54f48859076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>e304f0dc-85e8-4b1a-8ec7-b4bd60de7e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>newbtn360 blue btn btn-block</value>
      <webElementGuid>c5153518-1144-461f-a842-c6712e50bdea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>callDataLayer('Click','Cart','Nav-Buttons','Next');CartContinue()</value>
      <webElementGuid>521df3ee-f6ae-4d3f-8a0b-0d4ed9613d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{disabled : !CanContinue()}</value>
      <webElementGuid>3251e572-04e3-48e3-b7a2-489f39c40b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>474a08cb-5fd0-442c-9c11-190c99cbd685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Next&quot;)</value>
      <webElementGuid>81bbaff5-351e-48a3-8250-6dcb5b1c6c28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Next']</value>
      <webElementGuid>5e0d7923-db33-401e-81b1-f7fc7db6957a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[6]/div/div/div/div/div[3]/div[2]/div</value>
      <webElementGuid>c70d7d8c-633d-40f3-b613-770e8cd6ed3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy more products'])[2]/following::div[2]</value>
      <webElementGuid>eb250f11-4c00-42d7-862c-da505a13d567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy more products'])[1]/following::div[2]</value>
      <webElementGuid>f38ea60a-f361-4d97-b3e8-1eaddabc979e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basket'])[3]/preceding::div[1]</value>
      <webElementGuid>30295447-95e8-47cb-add2-63f92847a66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The cart is empty.'])[2]/preceding::div[2]</value>
      <webElementGuid>3c771c46-f22a-4b16-9c69-301f3dcd08e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>1e177470-a86b-4d9f-985a-ead9afb000ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div</value>
      <webElementGuid>e680253f-4296-4284-a8b2-5571d0c2dde6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Next' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>b61c865c-97ef-4561-ae65-03d6b05cf5c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
