<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Entrar  Registar</name>
   <tag></tag>
   <elementGuidId>ae96aadd-736b-4b3f-87a1-c4b6b131c1e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-register</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='login-register']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>521401b3-2aa1-4d27-ba57-ed0fcd5a51b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-table-vertical show-upselling-modal</value>
      <webElementGuid>297943eb-e03a-40cf-90ba-952e0f2a22d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Account/Login</value>
      <webElementGuid>3a66226e-1a47-4501-b262-7b1bf4c44244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-register</value>
      <webElementGuid>bf2600ea-c63c-4122-a0f8-5880dacebad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Área do Cliente</value>
      <webElementGuid>99db73a8-59cd-432e-99ff-dca762320740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventregion</name>
      <type>Main</type>
      <value>MENU</value>
      <webElementGuid>1fb836d7-9857-4bef-b4f6-e046a0e43e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventsection</name>
      <type>Main</type>
      <value>ACCOUNT</value>
      <webElementGuid>37b330de-a320-407f-9e28-594b38252243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventitem</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>a6f49b3e-b403-4233-91f0-d484d4337fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Entrar / Registar
        </value>
      <webElementGuid>973a5681-0009-4dc0-a934-1f88a0652717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-register&quot;)</value>
      <webElementGuid>03dda110-0ca8-4804-bae8-927eb110e865</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='login-register']</value>
      <webElementGuid>bc4d79b6-e23e-42bf-a10d-0a04830f109c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrap']/div[2]/div/div[3]/div/div[4]/div/div[6]/a</value>
      <webElementGuid>783602d5-902a-4488-9801-822b3b55ff1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Entrar / Registar')]</value>
      <webElementGuid>529cd725-d331-40c1-8130-7c0a5c237db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mais produtos'])[1]/following::a[5]</value>
      <webElementGuid>bb468faa-46ab-409c-a015-e9c5a527e220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[1]/following::a[6]</value>
      <webElementGuid>0a4a5de5-b849-456e-a112-dc7ec8e760b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/preceding::a[5]</value>
      <webElementGuid>b8802087-3af8-456a-9962-b3e444a94138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voltar'])[1]/preceding::a[5]</value>
      <webElementGuid>b76035ad-04b0-4bc0-8467-e51e3777a716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entrar / Registar']/parent::*</value>
      <webElementGuid>cb7494ad-3d27-4d93-8806-d729b1954d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Account/Login')]</value>
      <webElementGuid>7cfc709d-7a71-498d-8ed7-db5e998a36cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>5defe217-9831-4051-adf5-044edd7d0465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Account/Login' and @id = 'login-register' and @title = 'Área do Cliente' and (text() = '
            Entrar / Registar
        ' or . = '
            Entrar / Registar
        ')]</value>
      <webElementGuid>ba15c58c-7d45-4d5a-a685-471da09043b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
