<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aceito</name>
   <tag></tag>
   <elementGuidId>9efbd4b0-e9af-4fb7-a9ac-d2168c316aac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='onesignal-slidedown-allow-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#onesignal-slidedown-allow-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26ec44bb-45a3-4159-bb8f-55c22d584256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-right primary slidedown-button</value>
      <webElementGuid>58b82095-5e9b-4320-8c2b-9f61ed8d862f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onesignal-slidedown-allow-button</value>
      <webElementGuid>6b82f4c5-74bc-471b-913e-85d72bd31741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceito</value>
      <webElementGuid>db79b4aa-294a-4ee0-b065-6fc9fc1987f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onesignal-slidedown-allow-button&quot;)</value>
      <webElementGuid>481f22c2-f80b-4f10-a5f3-8b3183758455</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='onesignal-slidedown-allow-button']</value>
      <webElementGuid>816d6cf2-9895-4422-b726-6ef645c8efaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slidedown-footer']/button</value>
      <webElementGuid>3a7015ce-94f6-4e22-bd1b-65ec87d00c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gostaríamos de lhe enviar notificações com as principais novidades.'])[1]/following::button[1]</value>
      <webElementGuid>7f1ca423-69a2-4cd3-aa16-e195455b32e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[1]/following::button[1]</value>
      <webElementGuid>5d578016-85b3-49d9-a395-003a2e99b226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Não, obrigado'])[1]/preceding::button[1]</value>
      <webElementGuid>0608528a-fa87-43b0-ae76-f77295bc97f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aceito']/parent::*</value>
      <webElementGuid>314d488d-469e-4f2f-a82d-800f5a72ed99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/button</value>
      <webElementGuid>c792fc1a-f29f-484f-bb5f-fc732a058e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'onesignal-slidedown-allow-button' and (text() = 'Aceito' or . = 'Aceito')]</value>
      <webElementGuid>aca57854-c245-471b-84f9-eba3cf04b570</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
