<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Carrinho            (0)</name>
   <tag></tag>
   <elementGuidId>9f60b74e-d012-413d-855c-488f6a5dfc3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cartAndNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cartAndNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0ed173de-c20e-4c6e-ad3f-d879abcc3a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cartAndNumber</value>
      <webElementGuid>a66a40b9-97a9-4579-a282-75c87db43d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Carrinho
            (0)
        </value>
      <webElementGuid>8d094c21-3b93-469d-b69f-3a948a30937e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartAndNumber&quot;)</value>
      <webElementGuid>473b704a-1db5-4937-87ba-b1cd97631ece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cartAndNumber']</value>
      <webElementGuid>7bac6189-1ae6-48fd-96ba-dddd4732952a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='carBtnHeader']/span</value>
      <webElementGuid>e036a154-242a-4b7e-997e-afba42892f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satisfação garantida'])[1]/following::span[2]</value>
      <webElementGuid>0a29bcf4-b552-4c05-a31c-ccad2e71eca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se conseguir encontrar um preço mais baixo, nós igualamos.'])[1]/following::span[5]</value>
      <webElementGuid>87f3219f-05c0-4853-a834-64a1b241b00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mais produtos'])[1]/preceding::span[4]</value>
      <webElementGuid>c8ec923c-4435-48cd-84c8-0f6ac54365be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Carrinho']/parent::*</value>
      <webElementGuid>dd694b65-afe7-4c69-83e1-360858dd075d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>a6396088-a979-4284-99c2-e92dcbce69f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cartAndNumber' and (text() = '
            Carrinho
            (0)
        ' or . = '
            Carrinho
            (0)
        ')]</value>
      <webElementGuid>3e4af3c1-b21c-4c2d-83b7-2dd92c15102e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
