<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Escolher este design</name>
   <tag></tag>
   <elementGuidId>9ff031cd-aee4-4510-91a8-632929e4c95d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chooseBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='chooseBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>790e6cbc-6db5-43a2-9648-58a0323feb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chooseBtn</value>
      <webElementGuid>b9cf5fb9-9d0d-4a49-bb6a-b05353b29975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>chooseThisTemplate()</value>
      <webElementGuid>f8a1626c-f379-458b-bfda-5735a3803c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isLoading</value>
      <webElementGuid>104444c0-f1ba-463c-af65-f4dd0254ee90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> btn btn-primary btn-md col-xs-6 select-buttons</value>
      <webElementGuid>9e9800c4-1c07-4640-9817-a4bfbb16a374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Escolher este design 
                                </value>
      <webElementGuid>0d56642e-5d4a-41bf-bc7f-6e0dfe85ff96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chooseBtn&quot;)</value>
      <webElementGuid>585478fa-cf86-4c1b-9690-c9611ad650f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='chooseBtn']</value>
      <webElementGuid>8700e630-5f48-44b5-a04d-075efa842bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='templateDetailsModal']/div/div/div/div/div[3]/button</value>
      <webElementGuid>2876b0b7-1077-4970-a3fe-2155fdcf8004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grátis'])[1]/following::button[1]</value>
      <webElementGuid>4c082d2a-7c17-47a8-b271-e248b6f6990b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Como funciona?'])[1]/preceding::button[2]</value>
      <webElementGuid>66f49dbb-6ae5-446d-8f26-37bdffb79099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diga-nos o que pretende e a nossa equipa cria um design à sua medida!'])[1]/preceding::button[2]</value>
      <webElementGuid>80961e01-d263-4cf0-a951-a89edb5c71ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Escolher este design']/parent::*</value>
      <webElementGuid>60f63803-001b-4a97-bdec-4257986de704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/button</value>
      <webElementGuid>641da657-16a2-4639-ac32-29c96344540c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'chooseBtn' and (text() = '
                                    Escolher este design 
                                ' or . = '
                                    Escolher este design 
                                ')]</value>
      <webElementGuid>ea7e98ef-ac6d-449f-98e7-6ae5aa24c2bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
