<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login  Register</name>
   <tag></tag>
   <elementGuidId>c9dc01f5-1bf3-481b-8685-65329364c2f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='login-register']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login-register</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a31af23f-b2ed-4181-ab54-b462eb273987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-table-vertical show-upselling-modal</value>
      <webElementGuid>e6ebfc3e-cfbe-4e76-b59f-89b2e091f6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Account/Login</value>
      <webElementGuid>ea140c3f-f833-44d6-b188-3416bf4759f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-register</value>
      <webElementGuid>309292f4-8f69-4fb6-867b-8161c2e3393b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Client Area</value>
      <webElementGuid>f27b141d-8ec1-4956-93fb-fe1ddc2431e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventregion</name>
      <type>Main</type>
      <value>MENU</value>
      <webElementGuid>2be733d3-ed06-4b21-a49f-84df9fe71fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventsection</name>
      <type>Main</type>
      <value>ACCOUNT</value>
      <webElementGuid>0457dcd6-3afb-49db-9ca6-cef705fc69d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-eventitem</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>5a3ca0a1-720b-4520-b092-e12bbfaa826e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Login / Register
        </value>
      <webElementGuid>b31a59eb-9344-41fc-9254-c1461958d931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-register&quot;)</value>
      <webElementGuid>ed377022-b7bb-48c1-9d95-6ccc7f397ad8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='login-register']</value>
      <webElementGuid>d74a6269-6669-422c-a349-39bbd2d4ae9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrap']/div[2]/div/div[3]/div/div[4]/div/div[6]/a</value>
      <webElementGuid>3f595cdd-d829-4194-9af2-c7efb7b5351c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login / Register')]</value>
      <webElementGuid>d4c0b5a6-85ec-465b-a3a5-05234376b8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other products'])[1]/following::a[5]</value>
      <webElementGuid>af2be994-fa97-45ab-a88c-c14347f7a0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[1]/following::a[6]</value>
      <webElementGuid>4cc5a720-ead6-478a-a960-d1eb1995c8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/preceding::a[5]</value>
      <webElementGuid>245d3fb5-64f8-459d-aeb4-b9596be480bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return'])[1]/preceding::a[5]</value>
      <webElementGuid>ba127637-d6ec-44be-918e-ac8aed30b2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login / Register']/parent::*</value>
      <webElementGuid>6fff72c8-41c3-452d-b2ba-22d9bc68a3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Account/Login')]</value>
      <webElementGuid>eb4ad7b3-f7e9-402f-8cbf-fb7fe0f08ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>6b6c1726-2b80-47dd-a760-09ebff6696e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Account/Login' and @id = 'login-register' and @title = 'Client Area' and (text() = '
            Login / Register
        ' or . = '
            Login / Register
        ')]</value>
      <webElementGuid>619ac5cd-c31b-4b76-b5ea-078c188e0c77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
