<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Free_icon-trash</name>
   <tag></tag>
   <elementGuidId>45214865-a40a-49af-8555-4f3c90403054</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[6]/div/div/div/div/div[2]/table/tbody/tr[2]/td[4]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7b2c3d91-13cc-4eb5-aa85-f844a94ccc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-trash</value>
      <webElementGuid>f7351dec-a709-4f94-bf9b-eff26d6aa603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 page_envelope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;hidden-xs visible-sm visible-md visible-lg&quot;]/div[2]/table[@class=&quot;table table-cart&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[4]/a[@class=&quot;btn btn-default&quot;]/i[@class=&quot;icon-trash&quot;]</value>
      <webElementGuid>621e5495-8c5a-4d17-84b2-dfd798ea5887</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[6]/div/div/div/div/div[2]/table/tbody/tr[2]/td[4]/a/i</value>
      <webElementGuid>17fd10f3-4a86-43c9-a814-430f1750e1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>2dac6254-437b-46f2-86a8-b8d172b1c04e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
