<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Seguinte</name>
   <tag></tag>
   <elementGuidId>28d92587-965f-4afb-ac3c-b99bbfef9494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Next']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6158d7cf-d7ae-4d4e-bea1-eff3439d4c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>9bdebfbc-29b0-43c0-b538-8b7e7972f746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>newbtn360 blue btn btn-block</value>
      <webElementGuid>b0fee273-a251-47b0-a097-f834142a6a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>callDataLayer('Click','Cart','Nav-Buttons','Next');CartContinue()</value>
      <webElementGuid>f807efc0-bb74-47a2-aca0-915754eb8d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{disabled : !CanContinue()}</value>
      <webElementGuid>72524c32-08e0-402b-bbdb-4eccb49b61ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seguinte</value>
      <webElementGuid>e66b407a-efff-4057-a7e0-10d4d22f3bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Next&quot;)</value>
      <webElementGuid>bd3a07fe-4090-4d0a-8330-61b4b98fdbd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Next']</value>
      <webElementGuid>14b3f1d9-36d9-42e3-8f21-5d5b61972d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[6]/div/div/div/div/div[3]/div[2]/div</value>
      <webElementGuid>74b5fd92-ad19-4884-9abf-ef7c77bdc163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar mais produtos'])[2]/following::div[2]</value>
      <webElementGuid>4c577c38-2a8e-4646-95d9-27eb85323e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar mais produtos'])[1]/following::div[2]</value>
      <webElementGuid>86321c73-4c24-4c3f-bd2e-e85fb588d20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carrinho'])[2]/preceding::div[1]</value>
      <webElementGuid>ee77f71d-39bd-4343-b96d-7c17a024f4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O carrinho está vazio.'])[2]/preceding::div[2]</value>
      <webElementGuid>c4db1a79-9236-4723-97a3-56a38617b1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seguinte']/parent::*</value>
      <webElementGuid>6c288990-a109-4bb3-aff2-495f0e7c77cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div</value>
      <webElementGuid>39ae7bf8-3c4e-49a0-aefb-d2b3f0eba0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Next' and (text() = 'Seguinte' or . = 'Seguinte')]</value>
      <webElementGuid>1eaaf208-dd88-4241-9e14-e1f03db9e6fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
