<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Carrinho            (2)</name>
   <tag></tag>
   <elementGuidId>14baa873-22cb-47fb-9176-c737591306ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cartAndNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cartAndNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dd165db6-993e-4bd7-bd60-b7fb8ce10155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cartAndNumber</value>
      <webElementGuid>82f416e1-c29f-4bed-9e7f-57d4df184dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Carrinho
            (2)
        </value>
      <webElementGuid>d0eb34ba-765d-4184-be87-7fd2e9102441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartAndNumber&quot;)</value>
      <webElementGuid>2f7f7963-0c47-4e03-affd-872bf4973c2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='cartAndNumber']</value>
      <webElementGuid>ee8dd964-d7b1-4004-9ee0-79a6d5aafbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='carBtnHeader']/span</value>
      <webElementGuid>7cc9acaa-a695-447b-aa13-76cf31fc9aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satisfação garantida'])[1]/following::span[2]</value>
      <webElementGuid>5aee9f3c-dd2a-4b31-b61a-c37e56d811ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se conseguir encontrar um preço mais baixo, nós igualamos.'])[1]/following::span[5]</value>
      <webElementGuid>8c3f4224-a4c8-49e6-88cd-c70adbe522fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mais produtos'])[1]/preceding::span[4]</value>
      <webElementGuid>23a91dd3-b693-4d3b-b933-090876c3fd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Carrinho']/parent::*</value>
      <webElementGuid>c15f7af4-ea74-4c59-822f-22ee80f668b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>ad3110d1-0542-4ea4-9489-e36900446735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'cartAndNumber' and (text() = '
            Carrinho
            (2)
        ' or . = '
            Carrinho
            (2)
        ')]</value>
      <webElementGuid>088e6f2a-bdeb-4c46-a922-162962fb9a70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
