<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d2bb5fa3-ea71-4974-998e-f4fae434a651</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;mobile menu&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='toggleMobileMenu-v2']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>78944495-6537-493f-9acd-84f57a2f455d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>af652aa4-ca51-4129-b0f0-c0ea531f17eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Images/Mobile/mobile-menu-header.png?version=583709967142ae7f667d020ca687959c</value>
      <webElementGuid>ab20c643-3be3-462e-91b0-8ef9b2a3d7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>mobile menu</value>
      <webElementGuid>f72aaa09-3705-4be6-93ab-795235401915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggleMobileMenu-v2&quot;)/img[1]</value>
      <webElementGuid>45a61493-dc52-43ea-8bf2-7a60d5b204d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='toggleMobileMenu-v2']/img</value>
      <webElementGuid>8068df6f-37eb-409c-9d66-b0cbea698827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='mobile menu']</value>
      <webElementGuid>f1dcdd46-e458-4f94-a3ec-39f864ef5fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a/img</value>
      <webElementGuid>ef3c3c70-beb3-4c1b-b176-022fafe180af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Images/Mobile/mobile-menu-header.png?version=583709967142ae7f667d020ca687959c' and @alt = 'mobile menu']</value>
      <webElementGuid>35c078ab-4cb2-4faf-90fb-4031dc35f7ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
