<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Vinil para cho 297 x 420 mm (A3) Sem extra</name>
   <tag></tag>
   <elementGuidId>304e400e-7461-4296-afc0-b9b0dd0218d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='algolia-context-search']/div/div[2]/div[2]/div[2]/div[2]/ul/li[3]/div[2]/div/a/div[3]/div/h3/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>de750c23-e242-4abf-b486-290858131807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ais-Highlight-nonHighlighted custom-highlight</value>
      <webElementGuid>980354ef-11e2-474c-9e74-59dd4dfa3fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vinil para chão 297 x 420 mm (A3) Sem extra</value>
      <webElementGuid>26aee164-b5fd-430d-833c-9ab079ed6868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;context-pages&quot;)/div[@id=&quot;algolia-context-search&quot;]/div[@class=&quot;ais-InstantSearch__root&quot;]/div[@class=&quot;col-sm-9 right-panel&quot;]/div[2]/div[2]/div[@class=&quot;ais-Hits&quot;]/ul[@class=&quot;ais-Hits-list&quot;]/li[@class=&quot;ais-Hits-item&quot;]/div[@class=&quot;hit hidden-xs&quot;]/div[@class=&quot;hit-wrapper&quot;]/a[@class=&quot;hit-url&quot;]/div[@class=&quot;product-desc-wrapper&quot;]/div[@class=&quot;hit-title title-2-lines&quot;]/h3[@class=&quot;ais-Highlight custom-ais-highlight&quot;]/span[@class=&quot;ais-Highlight-nonHighlighted custom-highlight&quot;]</value>
      <webElementGuid>b003816e-ed31-4c5a-a723-348bee12a3c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='algolia-context-search']/div/div[2]/div[2]/div[2]/div[2]/ul/li[3]/div[2]/div/a/div[3]/div/h3/span</value>
      <webElementGuid>07005e58-6720-4394-971b-34edfa2b9edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promoção'])[6]/following::span[1]</value>
      <webElementGuid>6364c7a1-0cd5-4dd2-acc0-986e6938534d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div[2]/div/a/div[3]/div/h3/span</value>
      <webElementGuid>ca7a462b-f057-4535-b5b9-5272bda3b7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Vinil para chão 297 x 420 mm (A3) Sem extra' or . = 'Vinil para chão 297 x 420 mm (A3) Sem extra')]</value>
      <webElementGuid>e381e9b7-7b17-443a-82a3-d54e76307fce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
