<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login Same Market Alpha</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>19c0981d-7416-4294-a3a7-be7111116acb</testSuiteGuid>
   <testCaseLink>
      <guid>520611b9-f85f-495a-b07b-f61dda6f4c97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Suporte/Login - Variable - Same Market - Alpha</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>244ef6c9-aedc-4e0f-8de8-8a1a9292c90f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ObjectsSameMarket-Alpha</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>244ef6c9-aedc-4e0f-8de8-8a1a9292c90f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>openbrowser</value>
         <variableId>12d7375d-ec8a-40d6-8cc3-5b5c49a8d7d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>244ef6c9-aedc-4e0f-8de8-8a1a9292c90f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>entry</value>
         <variableId>3b4a96f4-6c09-4c5c-aa9a-af7e34dcb056</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>244ef6c9-aedc-4e0f-8de8-8a1a9292c90f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>start</value>
         <variableId>6f0d5b05-f4ac-4b04-9c3b-79823d85314b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>244ef6c9-aedc-4e0f-8de8-8a1a9292c90f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>myaccount</value>
         <variableId>18c8ffb5-f5e0-4eb2-84d1-a0a0d8d66a52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>244ef6c9-aedc-4e0f-8de8-8a1a9292c90f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>exit</value>
         <variableId>3b41572c-063e-4431-afa2-923a135bf7d7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
