<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__UserName</name>
   <tag></tag>
   <elementGuidId>b9e8a2e0-aef1-4414-94f6-1852d90dfd10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserNameLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UserNameLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f031cafc-343a-49b2-a5dd-c942ae7411f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0909fdb6-1d1f-4c16-b932-3ffc07f5334b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d048704b-9e6e-4ca5-99fb-40a5bdd210b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>O campo e-mail não pode exceder os 56 caracteres.</value>
      <webElementGuid>c8dadd0a-6125-442a-9edc-e8d996dfcd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>519f9027-48f7-4533-95e4-3c56ba30e1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>O campo 'Email' é obrigatório.</value>
      <webElementGuid>91f82ce7-46e6-4723-bdc4-9c948ccee8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserNameLogin</value>
      <webElementGuid>8b82d5a7-2db5-48a1-bb55-1dff09f2c166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserName</value>
      <webElementGuid>ac0b3a71-d18c-479b-a8f4-f00e68e83545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>callDataLayer('Click','Account_Login','Login','UserName')</value>
      <webElementGuid>b9e3b992-4700-45e8-9d0f-e2fa23260747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>24d22608-cc58-4450-b179-2fe2b3bf3e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a3aa3a2f-f09b-4a09-b193-bf9c2b574ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserNameLogin&quot;)</value>
      <webElementGuid>a47b5921-fa93-43c8-b93b-08fd64af2f43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UserNameLogin']</value>
      <webElementGuid>d9c1f2fb-6c86-41c2-b8c2-924f2d24ea8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseLoginForm']/form/div[2]/div[2]/input</value>
      <webElementGuid>7764345a-a6a3-48e0-a8a2-ce0904e21507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/form/div[2]/div[2]/input</value>
      <webElementGuid>dca27215-c4ab-4ad1-bd9e-e196e8692eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UserNameLogin' and @name = 'UserName' and @placeholder = 'Email' and @type = 'email']</value>
      <webElementGuid>1c7b8d85-f693-4f0f-a2c0-9e37aaac2261</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
