<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ConfirmUserName</name>
   <tag></tag>
   <elementGuidId>22ff4d05-c9b6-4e9f-887c-722e9c9056bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ConfirmUserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ConfirmUserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9540ba8f-ce51-48e6-93f4-a1d765bed4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>386baa55-5c94-46e4-a05d-8fced21749a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ccbd197-ed33-4207-82e7-ba0f3ac2142b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto</name>
      <type>Main</type>
      <value>Os emails são diferentes.</value>
      <webElementGuid>8fe9c817-3efe-43d8-871b-802bab698ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto-other</name>
      <type>Main</type>
      <value>*.UserName</value>
      <webElementGuid>fb25db2e-326c-460a-8caa-e8e2fd98c62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>O campo 'Confirmar Email' é obrigatório.</value>
      <webElementGuid>611a5974-3ffd-4142-ad11-f89ecb8dca21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConfirmUserName</value>
      <webElementGuid>480c6a45-9978-4d62-a95f-ccce6d761fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ConfirmUserName</value>
      <webElementGuid>839b33c8-1f6c-448f-9779-01116a55c9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>callDataLayer('Click','Account_Login','Registo','ConfirmUserName')</value>
      <webElementGuid>973a2de1-f5fc-4e35-a78d-34019e2544d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirmar Email</value>
      <webElementGuid>36f77f9b-96fa-4840-99b8-2c30b4aad7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>383b11da-f14e-4b61-9076-4f07afd33d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConfirmUserName&quot;)</value>
      <webElementGuid>a29be171-e1e2-4176-99d4-5011a683d846</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ConfirmUserName']</value>
      <webElementGuid>35af3d95-ec9e-42f0-866e-fead0ec30ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='colapseRegisterForm']/form/div[2]/div[3]/input</value>
      <webElementGuid>27906717-ac7d-48f1-8f47-5266b3a0af80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>6b8e437f-4553-4de3-81ec-23886d5c67c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ConfirmUserName' and @name = 'ConfirmUserName' and @placeholder = 'Confirmar Email' and @type = 'email']</value>
      <webElementGuid>87eb30c6-8609-4161-88e3-ef624824c189</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
