<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gr-Bretanha</name>
   <tag></tag>
   <elementGuidId>24ac14b5-d127-41b5-b469-21523c13aa64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#culture-item-default-market-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='culture-item-default-market-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ca226dea-ebc3-455e-93bf-bb4ac11ae6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>market-label market</value>
      <webElementGuid>5e631437-1f60-4956-9736-2ff480f448fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>culture-item-default-market-5</value>
      <webElementGuid>f20cc89d-696e-4294-977e-090f68045a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://alpha.bizay.co.uk/en-gb/</value>
      <webElementGuid>c7dcc1d8-6333-4ec4-9525-906c4dd79d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return notMakeRequest();</value>
      <webElementGuid>32e6771e-a849-4064-9ddd-78cb46662dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grã-Bretanha </value>
      <webElementGuid>1bfc92f3-76ff-4512-af4e-97210d3a44d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;culture-item-default-market-5&quot;)</value>
      <webElementGuid>5779483e-b1e7-44ec-aa07-4c695c850776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='culture-item-default-market-5']</value>
      <webElementGuid>08e79695-f7f6-457d-aed2-c3c12652c9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='country']/a)[5]</value>
      <webElementGuid>384dc4dc-8fa3-47cb-aaba-992b37bfaf1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Grã-Bretanha')]</value>
      <webElementGuid>6df0a707-f93f-47ec-a9cb-b9ed5938e317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ES'])[3]/following::a[1]</value>
      <webElementGuid>4482e30c-6df1-476e-a0e8-9ca49fe6b819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mexico'])[1]/following::a[2]</value>
      <webElementGuid>267f6f97-c473-42e3-bfef-bbdd23ac3ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/preceding::a[1]</value>
      <webElementGuid>89a1ad5f-ba69-4f4d-9c55-0e285b2bb4f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='França'])[1]/preceding::a[2]</value>
      <webElementGuid>22bff943-ebcc-46d1-a8a0-bcfdce112075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grã-Bretanha']/parent::*</value>
      <webElementGuid>4fd60d9d-d0ac-4c4f-b4b3-d508ab9bda07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://alpha.bizay.co.uk/en-gb/')]</value>
      <webElementGuid>7393056e-8037-4a97-93f0-958aa599ce2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/a</value>
      <webElementGuid>aa1aa9eb-dde5-4aab-8a38-7cecc44df58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'culture-item-default-market-5' and @href = 'https://alpha.bizay.co.uk/en-gb/' and (text() = 'Grã-Bretanha ' or . = 'Grã-Bretanha ')]</value>
      <webElementGuid>d6d0dde3-a35f-457f-9110-60f4be480d42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
