<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Portugal</name>
   <tag></tag>
   <elementGuidId>b092784d-653d-47b9-ac7e-c2c9559596ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='languageSwitcher']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#languageSwitcher > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>59acf44f-10cf-40dd-bb96-ce8d8c6c6dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Portugal |</value>
      <webElementGuid>a63c424c-52c9-4147-ada3-ec47b31ce451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;languageSwitcher&quot;)/span[1]</value>
      <webElementGuid>2202db80-0f79-4fbe-87d9-ffbb395ec27d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='languageSwitcher']/span</value>
      <webElementGuid>a1ca2392-75b1-4b87-b175-c4ec4267b3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serviço Apoio ao Cliente'])[1]/following::span[1]</value>
      <webElementGuid>868c915b-719e-4245-9388-d4da7a7b3837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT'])[1]/preceding::span[1]</value>
      <webElementGuid>06cc09a4-bdde-43d8-891b-0eae03f3fcee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portugal'])[1]/preceding::span[2]</value>
      <webElementGuid>459cd881-f5e8-4c82-85f2-013733813e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Portugal |']/parent::*</value>
      <webElementGuid>aa27384a-8501-46f5-8b24-44225ddd0e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/span</value>
      <webElementGuid>00854244-9e4d-4815-9e48-1baccb71d47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Portugal |' or . = ' Portugal |')]</value>
      <webElementGuid>d0bb44c4-d8fe-4c92-a375-084a8b08fdfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
