<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Brasil</name>
   <tag></tag>
   <elementGuidId>902aa5f2-3cd4-4c39-af57-312f4465e92c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='culture-item-default-market-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#culture-item-default-market-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e766d87f-9ad2-4af8-9eb0-02b45ad9c24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>market-label market</value>
      <webElementGuid>a5091868-fdca-4301-a266-95263dabe4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>culture-item-default-market-3</value>
      <webElementGuid>1a1cbc52-b8da-4b00-b6a2-981918e8507e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://alpha.360imprimir.com.br/pt-br/?_ga=2.236375171.300837281.1673897938-901441859.1673897938</value>
      <webElementGuid>c251782c-cd63-438d-a670-ed29d06b062a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return notMakeRequest();</value>
      <webElementGuid>924559f2-e05b-446f-95d1-77301cd12b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brasil </value>
      <webElementGuid>bf24678f-b9b1-45cc-aa6a-9b8692e44f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;culture-item-default-market-3&quot;)</value>
      <webElementGuid>34e2d181-f058-4fa8-a0ff-c0a309f22ad1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='culture-item-default-market-3']</value>
      <webElementGuid>2b742d81-a46a-44c9-bd4b-ff0fd041b2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='country']/a)[3]</value>
      <webElementGuid>5ded9b98-6f0a-404e-845e-1e6cc1f63537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Brasil')]</value>
      <webElementGuid>3ae8a247-067f-4234-baa3-7e32d92278be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ES'])[2]/following::a[1]</value>
      <webElementGuid>73b97dd2-f6f8-403c-ac28-74519e28f75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT'])[3]/following::a[2]</value>
      <webElementGuid>cbd5a64b-fac6-4862-8afa-fcdf8b5de22c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT'])[4]/preceding::a[1]</value>
      <webElementGuid>a2337500-edb6-4d48-bfbe-a55924264812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mexico'])[1]/preceding::a[2]</value>
      <webElementGuid>329e1aa7-f87f-4d05-b3b1-fb5db7224a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Brasil']/parent::*</value>
      <webElementGuid>af4b2b83-bbfe-47ca-93fe-afcaec3a744a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://alpha.360imprimir.com.br/pt-br/?_ga=2.236375171.300837281.1673897938-901441859.1673897938')]</value>
      <webElementGuid>2178b128-35c3-45ff-b6ee-bbf8db26e24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/a</value>
      <webElementGuid>0fb70dee-2bc3-453e-890d-86685347c3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'culture-item-default-market-3' and @href = 'https://alpha.360imprimir.com.br/pt-br/?_ga=2.236375171.300837281.1673897938-901441859.1673897938' and (text() = 'Brasil ' or . = 'Brasil ')]</value>
      <webElementGuid>57ba9bb7-577a-4a30-b1d2-031ceb6e681e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
