<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Autocolantes</name>
   <tag></tag>
   <elementGuidId>a7716129-85ac-4d70-9070-173f033081e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='headeritem-2']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headeritem-2 > p.ellip.ellip-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2147ed99-83a8-4969-9853-efa7adbfcecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ellip ellip-2</value>
      <webElementGuid>64d6be6b-26f0-424e-9810-4b52bdf6cb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Autocolantes</value>
      <webElementGuid>a1f09bc8-ff1f-4df6-a4b6-a2017324d44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headeritem-2&quot;)/p[@class=&quot;ellip ellip-2&quot;]</value>
      <webElementGuid>0971cfe3-cecc-4893-a63b-0ddec15e1c26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='headeritem-2']/p</value>
      <webElementGuid>43c25a4d-caee-43a9-85af-c191cd9e528c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mais produtos'])[1]/following::p[3]</value>
      <webElementGuid>84326881-844d-406c-9913-2dc1ffc391a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1)'])[1]/following::p[3]</value>
      <webElementGuid>846c7ef3-e387-41b7-8a8e-ad696c9a05e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dados da Conta'])[1]/preceding::p[2]</value>
      <webElementGuid>f07823ee-1eaf-4a3b-8e19-366c97daffff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Endereços'])[1]/preceding::p[2]</value>
      <webElementGuid>8733f643-c51e-44d6-b34b-9fcf70e262b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Autocolantes']/parent::*</value>
      <webElementGuid>d7f7dbe5-7ba5-42ef-8e65-338a41ab14ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/p</value>
      <webElementGuid>a506680a-91eb-4008-a032-3bf71a4ef6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Autocolantes' or . = 'Autocolantes')]</value>
      <webElementGuid>6d237444-ded3-4867-8cfe-0558aee10533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
