<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cartes de Visita 55 x 85 mm (Formato E_093126</name>
   <tag></tag>
   <elementGuidId>f17d76f2-5941-4945-83a8-8a417f63bae8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='algolia-context-search']/div/div[2]/div[2]/div[2]/div[2]/ul/li[2]/div[2]/div/a/div[3]/div/h3/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c01f020d-e9ff-40af-abcf-099154a7dfec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ais-Highlight-nonHighlighted custom-highlight</value>
      <webElementGuid>2d41c964-162e-44b8-baff-b9060d5c2d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cartões de Visita 55 x 85 mm (Formato Europeu) Retangular</value>
      <webElementGuid>1daca4b1-b59a-4276-81d6-acd8e5a6cd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;context-pages&quot;)/div[@id=&quot;algolia-context-search&quot;]/div[@class=&quot;ais-InstantSearch__root&quot;]/div[@class=&quot;col-sm-9 right-panel&quot;]/div[2]/div[2]/div[@class=&quot;ais-Hits&quot;]/ul[@class=&quot;ais-Hits-list&quot;]/li[@class=&quot;ais-Hits-item&quot;]/div[@class=&quot;hit hidden-xs&quot;]/div[@class=&quot;hit-wrapper&quot;]/a[@class=&quot;hit-url&quot;]/div[@class=&quot;product-desc-wrapper&quot;]/div[@class=&quot;hit-title title-2-lines&quot;]/h3[@class=&quot;ais-Highlight custom-ais-highlight&quot;]/span[@class=&quot;ais-Highlight-nonHighlighted custom-highlight&quot;]</value>
      <webElementGuid>db89769e-5ee6-4184-bd7a-56ca815d213b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='algolia-context-search']/div/div[2]/div[2]/div[2]/div[2]/ul/li[2]/div[2]/div/a/div[3]/div/h3/span</value>
      <webElementGuid>23a8a761-0e31-4926-accd-1a390e7210b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promoção'])[4]/following::span[1]</value>
      <webElementGuid>b2af8e19-fda2-40d2-8b11-c632121f3263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]/div/a/div[3]/div/h3/span</value>
      <webElementGuid>d3837109-5451-4ea7-bb6a-f59ab7e82545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cartões de Visita 55 x 85 mm (Formato Europeu) Retangular' or . = 'Cartões de Visita 55 x 85 mm (Formato Europeu) Retangular')]</value>
      <webElementGuid>df2a159d-9a05-43b3-b211-2bd4fc2281e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
